/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { Account, accountSchema } from '../account';
import { Account1, account1Schema } from '../account1';
import { Account2, account2Schema } from '../account2';
import { Account3, account3Schema } from '../account3';
import { Account4, account4Schema } from '../account4';
import { Account5, account5Schema } from '../account5';

/** This is a container type for any-of types. */
export type AkoyaAccountInfoProductAccounts =
  | Account
  | Account1
  | Account2
  | Account3
  | Account4
  | Account5;

export const akoyaAccountInfoProductAccountsSchema: Schema<AkoyaAccountInfoProductAccounts> = anyOf(
  [
    accountSchema,
    account1Schema,
    account2Schema,
    account3Schema,
    account4Schema,
    account5Schema,
  ]
);

export namespace AkoyaAccountInfoProductAccounts {
  /**
   * Validation method to narrow down union type to Account type case.
   *
   * This is Account case.
   */
  export function isAccount(value: unknown): value is Account {
    const validationResult = validateAndMap(value, accountSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account1 type case.
   *
   * This is Account1 case.
   */
  export function isAccount1(value: unknown): value is Account1 {
    const validationResult = validateAndMap(value, account1Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account2 type case.
   *
   * This is Account2 case.
   */
  export function isAccount2(value: unknown): value is Account2 {
    const validationResult = validateAndMap(value, account2Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account3 type case.
   *
   * This is Account3 case.
   */
  export function isAccount3(value: unknown): value is Account3 {
    const validationResult = validateAndMap(value, account3Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account4 type case.
   *
   * This is Account4 case.
   */
  export function isAccount4(value: unknown): value is Account4 {
    const validationResult = validateAndMap(value, account4Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account5 type case.
   *
   * This is Account5 case.
   */
  export function isAccount5(value: unknown): value is Account5 {
    const validationResult = validateAndMap(value, account5Schema);
    return validationResult.errors === false;
  }
}
