/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { Account7, account7Schema } from '../account7';
import { Account71, account71Schema } from '../account71';
import { Account72, account72Schema } from '../account72';
import { Account74, account74Schema } from '../account74';
import { Account75, account75Schema } from '../account75';
import { Account9, account9Schema } from '../account9';

/** This is a container type for any-of types. */
export type InvestmentsAccounts =
  | Account9
  | Account7
  | Account71
  | Account72
  | Account74
  | Account75;

export const investmentsAccountsSchema: Schema<InvestmentsAccounts> = anyOf([
  account9Schema,
  account7Schema,
  account71Schema,
  account72Schema,
  account74Schema,
  account75Schema,
]);

export namespace InvestmentsAccounts {
  /**
   * Validation method to narrow down union type to Account9 type case.
   *
   * This is Account9 case.
   */
  export function isAccount9(value: unknown): value is Account9 {
    const validationResult = validateAndMap(value, account9Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account7 type case.
   *
   * This is Account7 case.
   */
  export function isAccount7(value: unknown): value is Account7 {
    const validationResult = validateAndMap(value, account7Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account71 type case.
   *
   * This is Account71 case.
   */
  export function isAccount71(value: unknown): value is Account71 {
    const validationResult = validateAndMap(value, account71Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account72 type case.
   *
   * This is Account72 case.
   */
  export function isAccount72(value: unknown): value is Account72 {
    const validationResult = validateAndMap(value, account72Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account74 type case.
   *
   * This is Account74 case.
   */
  export function isAccount74(value: unknown): value is Account74 {
    const validationResult = validateAndMap(value, account74Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Account75 type case.
   *
   * This is Account75 case.
   */
  export function isAccount75(value: unknown): value is Account75 {
    const validationResult = validateAndMap(value, account75Schema);
    return validationResult.errors === false;
  }
}
