/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { Transaction1, transaction1Schema } from '../transaction1';
import { Transaction11, transaction11Schema } from '../transaction11';
import { Transaction12, transaction12Schema } from '../transaction12';
import { Transaction13, transaction13Schema } from '../transaction13';
import { Transaction14, transaction14Schema } from '../transaction14';

/** This is a container type for any-of types. */
export type TransactionsEntityTransactions =
  | Transaction1
  | Transaction11
  | Transaction12
  | Transaction13
  | Transaction14;

export const transactionsEntityTransactionsSchema: Schema<TransactionsEntityTransactions> = anyOf(
  [
    transaction1Schema,
    transaction11Schema,
    transaction12Schema,
    transaction13Schema,
    transaction14Schema,
  ]
);

export namespace TransactionsEntityTransactions {
  /**
   * Validation method to narrow down union type to Transaction1 type case.
   *
   * This is Transaction1 case.
   */
  export function isTransaction1(value: unknown): value is Transaction1 {
    const validationResult = validateAndMap(value, transaction1Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Transaction11 type case.
   *
   * This is Transaction11 case.
   */
  export function isTransaction11(value: unknown): value is Transaction11 {
    const validationResult = validateAndMap(value, transaction11Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Transaction12 type case.
   *
   * This is Transaction12 case.
   */
  export function isTransaction12(value: unknown): value is Transaction12 {
    const validationResult = validateAndMap(value, transaction12Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Transaction13 type case.
   *
   * This is Transaction13 case.
   */
  export function isTransaction13(value: unknown): value is Transaction13 {
    const validationResult = validateAndMap(value, transaction13Schema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Transaction14 type case.
   *
   * This is Transaction14 case.
   */
  export function isTransaction14(value: unknown): value is Transaction14 {
    const validationResult = validateAndMap(value, transaction14Schema);
    return validationResult.errors === false;
  }
}
