/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type CurrentCustomer,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { customersController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface CustomerInfoMCPToolRequest {
  'version': string,
  'providerId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
}

async function executeCustomerInfo(
  req: CustomerInfoMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await customersController.customerInfo(
      req['version'],
      req['providerId'],
      req['x-akoya-interaction-type']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleCustomerInfo(
  args: unknown | CustomerInfoMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Customers", "customer-info");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for customerInfo tool." }],
      isError: true,
    };
  }

  return await executeCustomerInfo(args as CustomerInfoMCPToolRequest);
}

export async function customersCustomerInfoTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "customers-customerInfo",
      description: `This product supports use cases such as payment enablement, account opening, and identity verification. Responses return information about the authorized end-user, the customer associated with the \`id_token\` used in the call. This information may include, but is not limited to, the customer identifier, name, email, address, and phone number.

<br>

To see the response schema, select the \`200\` response below. For an example payload response, see the \`200\` example response below the *Try it* feature. 

This product requires consumer consent to share all account holder information.

> 🛑 The \`id_token\` should be used as the bearer token with this call.
> `,
      inputSchema: await schemas.loadSchema("Customers", "customer-info"),
    },
    handler: handleCustomerInfo,
  };
}

