/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type AccountContactEntity,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { customersController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetAccountHolderMCPToolRequest {
  'accountId': string,
  'version': string,
  'providerId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
}

async function executeGetAccountHolder(
  req: GetAccountHolderMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await customersController.getAccountHolder(
      req['accountId'],
      req['version'],
      req['providerId'],
      req['x-akoya-interaction-type']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetAccountHolder(
  args: unknown | GetAccountHolderMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Customers", "get-account-holder");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getAccountHolder tool." }],
      isError: true,
    };
  }

  return await executeGetAccountHolder(args as GetAccountHolderMCPToolRequest);
}

export async function customersGetAccountHolderTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "customers-getAccountHolder",
      description: `This product supports use cases such as payment enablement, account opening, identity verification,or lending & credit enhancement. Responses return information about the authorized consumer, the customer associated with the \`id_token\` used in the call, and the relationship specific to the provided \`accountId\`.

> 📌 Please note!
>
> This endpoint provides additional information which may not be required for your use case, making it inefficient compared to the [/customer info](https://docs.akoya.com/reference/customer-info) endpoint. Please refer to to the [Customers guide](https://docs.akoya.com/reference/customers) for more information about this endpoint.

Get account holder information. Based on FDX 5.2.1.

This product requires consumer consent to share all account holder information.

> 🛑 The \`id_token\` should be used as the bearer token with this call.
> 
`,
      inputSchema: await schemas.loadSchema("Customers", "get-account-holder"),
    },
    handler: handleGetAccountHolder,
  };
}

