/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type AkoyaAccountInfoProduct,
  type XAkoyaInteractionTypeEnum,
  type ModeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { accountInformationController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetAccountsInfoMCPToolRequest {
  'version': string,
  'providerId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
  'mode': ModeEnum,
}

async function executeGetAccountsInfo(
  req: GetAccountsInfoMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await accountInformationController.getAccountsInfo(
      req['version'],
      req['providerId'],
      req['x-akoya-interaction-type'],
      req['mode']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetAccountsInfo(
  args: unknown | GetAccountsInfoMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Account information", "get-accounts-info");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getAccountsInfo tool." }],
      isError: true,
    };
  }

  return await executeGetAccountsInfo(args as GetAccountsInfoMCPToolRequest);
}

export async function accountInformationGetAccountsInfoTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "accountInformation-getAccountsInfo",
      description: `Get basic account information including accountId, masked account number, type, description, etc.

To view the response schema, select the \`200\` response below. Then pick an option for annuity, deposit, insurance, investment, loan, and line of credit account types. 

For an example payload response, see the \`200\` example response below the \`Try it\` feature. The example is from a deposit account but all account types are supported by this endpoint.

> 🛑
> 
> The *id_token* should be used as the bearer token with this call.

Use the \`mode\` query param to receive FDX-aligned, standardized data values (Beta). For example:

\`https://sandbox-products.ddp.akoya.com/accounts-info/v2/mikomo?mode=standard\`

\`mode\` is available in both sandbox and production.

\`mode\` is supported by a subset of providers. Log into the [Data Recipient Hub](https://recipient.ddp.akoya.com/login) and click [here](https://recipient.ddp.akoya.com/support/article/kA0Uw00000015GzKAI) to view a list of all providers supporting the \`mode\` parameter.

`,
      inputSchema: await schemas.loadSchema("Account information", "get-accounts-info"),
    },
    handler: handleGetAccountsInfo,
  };
}

