/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AccountInformationController,
  AkoyaAccountInfoProduct,
  BalanceTypeEnum,
  InterestRateTypeEnum,
  ModeEnum,
  StatusEnum,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('AccountInformationController', () => {
  let controller : AccountInformationController;

  beforeAll(() => {
    controller = new AccountInformationController(testClient);
  });

  it('should Test get-accounts-info', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getAccountsInfo(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: AkoyaAccountInfoProduct = {
      accounts: [
        {
        },
        {
        },
        {
          depositAccount: {
            accountId: 'g833202fb0866d0ad83472c429',
            accountType: 'CHECKING',
            accountNumberDisplay: 'xxxxxxxx0071',
            currency: {
              currencyCode: 'USD',
            },
            description: 'Checking Plus',
            fiAttributes: [
              {
                name: 'accountOpenedDate',
                value: '2020-04-23',
              },
              {
                name: 'interestPaidLastYear',
                value: '3.20',
              }
            ],
            nickname: 'Nickname Checking Plus 0071',
            productName: 'Checking Plus',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'Personal',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.0125,
            interestRateType: InterestRateTypeEnum.FIXED,
            interestRateAsOf: '2022-04-24T14:15:22Z',
            lastActivityDate: '2022-04-24T14:15:22Z',
            transferIn: true,
            transferOut: true,
          },
        },
        {
          depositAccount: {
            accountId: '5dbda8de96eeff05f23934523a1fc258',
            accountType: 'CHECKING',
            accountNumberDisplay: 'xxxx0134',
            currency: {
              currencyCode: 'USD',
            },
            description: 'Virtual Wallet Student Reserve',
            productName: 'Virtual Wallet Student Reserve',
            lineOfBusiness: 'LBRB',
            interestRateType: InterestRateTypeEnum.FIXED,
            interestRateAsOf: '2022-04-24T14:15:22Z',
            lastActivityDate: '2022-04-01T10:05:00Z',
            annualPercentageYield: 0,
          },
        },
        {
          depositAccount: {
            accountId: '11719ae5-2399-1278-e43c-43f24abb3058',
            accountType: 'CD',
            currency: {
              currencyCode: 'USD',
              originalCurrencyCode: 'USD',
            },
            description: 'Certificate of Deposit',
            fiAttributes: [
              {
                name: 'eStatements',
                value: 'False',
              },
              {
                name: 'interestPaidLastYear',
                value: '50.72',
              },
              {
                name: 'isTransactionsSupported',
                value: 'False',
              },
              {
                name: 'issueDate',
                value: '2019-03-21T00:00:00.000Z',
              },
              {
                name: 'interestPayoutFrequency',
                value: 'Semi-Annually (And At Maturity)',
              }
            ],
            nickname: 'Certificate of Deposit - 3691',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'CONSUMER',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.75,
            parentAccountId: '11719ae5-2399-1278-e43c-43f24abb3058',
            transferIn: false,
            transferOut: false,
            annualPercentageYield: 0.75,
            term: 60,
            maturityDate: '2024-03-21T00:00:00Z',
          },
        },
        {
          depositAccount: {
            accountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
            accountType: 'SAVINGS',
            currency: {
              currencyCode: 'USD',
              originalCurrencyCode: 'USD',
            },
            description: 'Savings',
            fiAttributes: [
              {
                name: 'eStatements',
                value: 'True',
              }
            ],
            nickname: 'Savings - 8537',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'CONSUMER',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.01,
            parentAccountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
          },
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test get-accounts-info1', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getAccountsInfo(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(206);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: AkoyaAccountInfoProduct = {
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
