/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  Balances,
  BalancesController,
  BalanceTypeEnum,
  InterestRateTypeEnum,
  ModeEnum,
  StatusEnum,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('BalancesController', () => {
  let controller : BalancesController;

  beforeAll(() => {
    controller = new BalancesController(testClient);
  });

  it('should Test get-balances', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getBalances(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Balances = {
      accounts: [
        {
        },
        {
        },
        {
          depositAccount: {
            accountId: 'g833202fb0866d0ad83472c429',
            accountType: 'CHECKING',
            accountNumberDisplay: 'xxxxxxxx0071',
            currency: {
              currencyCode: 'USD',
            },
            description: 'Checking Plus',
            fiAttributes: [
              {
                name: 'accountOpenedDate',
                value: '2020-04-23',
              },
              {
                name: 'interestPaidLastYear',
                value: '3.20',
              }
            ],
            nickname: 'Nickname Checking Plus 0071',
            productName: 'Checking Plus',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'Personal',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.0125,
            interestRateType: InterestRateTypeEnum.FIXED,
            interestRateAsOf: '2022-04-24T14:15:22Z',
            lastActivityDate: '2022-04-24T14:15:22Z',
            transferIn: true,
            transferOut: true,
            balanceAsOf: '2022-04-24T14:15:22Z',
            availableBalance: 106717.06,
            interestYtd: 20.33,
            currentBalance: 106717.06,
          },
        },
        {
          depositAccount: {
            accountId: '5dbda8de96eeff05f23934523a1fc258',
            accountType: 'CHECKING',
            accountNumberDisplay: 'xxxx0134',
            currency: {
              currencyCode: 'USD',
            },
            description: 'Virtual Wallet Student Reserve',
            productName: 'Virtual Wallet Student Reserve',
            lineOfBusiness: 'LBRB',
            interestRateType: InterestRateTypeEnum.FIXED,
            interestRateAsOf: '2022-04-24T14:15:22Z',
            lastActivityDate: '2022-04-01T10:05:00Z',
            annualPercentageYield: 0,
            balanceAsOf: '2022-04-24T14:15:22Z',
            openingDayBalance: 0,
            availableBalance: 0,
            currentBalance: 0,
          },
        },
        {
          depositAccount: {
            accountId: '11719ae5-2399-1278-e43c-43f24abb3058',
            accountType: 'CD',
            currency: {
              currencyCode: 'USD',
              originalCurrencyCode: 'USD',
            },
            description: 'Certificate of Deposit',
            fiAttributes: [
              {
                name: 'eStatements',
                value: 'False',
              },
              {
                name: 'interestPaidLastYear',
                value: '50.72',
              },
              {
                name: 'isTransactionsSupported',
                value: 'False',
              },
              {
                name: 'issueDate',
                value: '2019-03-21T00:00:00.000Z',
              },
              {
                name: 'interestPayoutFrequency',
                value: 'Semi-Annually (And At Maturity)',
              }
            ],
            nickname: 'Certificate of Deposit - 3691',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'CONSUMER',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.75,
            parentAccountId: '11719ae5-2399-1278-e43c-43f24abb3058',
            transferIn: false,
            transferOut: false,
            annualPercentageYield: 0.75,
            term: 60,
            maturityDate: '2024-03-21T00:00:00Z',
            balanceAsOf: '2021-04-07T10:20:43.276Z',
            openingDayBalance: 2000,
            availableBalance: 6808.29,
            interestYtd: 25.24,
            currentBalance: 6808.29,
          },
        },
        {
          depositAccount: {
            accountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
            accountType: 'SAVINGS',
            currency: {
              currencyCode: 'USD',
              originalCurrencyCode: 'USD',
            },
            description: 'Savings',
            fiAttributes: [
              {
                name: 'eStatements',
                value: 'True',
              }
            ],
            nickname: 'Savings - 8537',
            status: StatusEnum.OPEN,
            lineOfBusiness: 'CONSUMER',
            balanceType: BalanceTypeEnum.ASSET,
            interestRate: 0.01,
            parentAccountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
            balanceAsOf: '2021-04-07T10:08:11.833Z',
            openingDayBalance: 20608.9,
            availableBalance: 20608.9,
            interestYtd: 0.29,
            currentBalance: 20608.9,
          },
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test get-balances1', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getBalances(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(206);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Balances = {
      accounts: [
        {
        },
        {
          depositAccount: {
          },
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
