/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AccountContactEntity,
  AccountHolderRelationship2Enum,
  CustomersController,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('CustomersController', () => {
  let controller : CustomersController;

  beforeAll(() => {
    controller = new CustomersController(testClient);
  });

  it('should Test customer-info', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.customerInfo(version, providerId, xAkoyaInteractionType)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-account-holder', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getAccountHolder(
        accountId,
        version,
        providerId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: AccountContactEntity = {
      holders: [
        {
          relationship: AccountHolderRelationship2Enum.AUTHORIZEDUSER,
        }
      ],
      emails: [
        'string'
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
