/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AssetClass1Enum,
  BalanceTypeEnum,
  Investments,
  InvestmentsController,
  ModeEnum,
  MutualFundTypeEnum,
  PositionTypeEnum,
  SecurityIdTypeEnum,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('InvestmentsController', () => {
  let controller : InvestmentsController;

  beforeAll(() => {
    controller = new InvestmentsController(testClient);
  });

  it('should Test get-accounts', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getAccounts(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Investments = {
      accounts: [
        {
          investmentAccount: {
            accountId: '839502593',
            accountType: 'College Savings',
            currency: {
              currencyCode: 'USD',
            },
            nickname: '529 for Kid',
            balanceType: BalanceTypeEnum.ASSET,
            availableCashBalance: 0,
            balanceAsOf: '2022-03-16T04:00:00Z',
            currentValue: 52672.49,
            marginBalance: 0,
            holdings: [
              {
                assetClasses: [
                  {
                    assetClass: AssetClass1Enum.DOMESTICBOND,
                    percent: 0,
                  }
                ],
                cashAccount: false,
                marketValue: 52672.49,
                positionType: PositionTypeEnum.LONG,
                purchasedPrice: 18.42,
                securityIdType: SecurityIdTypeEnum.ISIN,
                units: 2088.521,
                mutualFundSecurity: {
                  mutualFundType: MutualFundTypeEnum.OPENEND,
                  unitsStreet: 0,
                  unitsUser: 0,
                  reinvestDividends: true,
                  reinvestCapitalGains: true,
                  yield: 0,
                  yieldAsOfDate: '2019-08-24T14:15:22Z',
                },
              }
            ],
          },
        },
        {
        },
        {
        },
        {
        },
        {
        },
        {
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test get-accounts1', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getAccounts(
        version,
        providerId,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(206);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Investments = {
      accounts: [
        {
          investmentAccount: {
            accountId: '839502593',
            accountType: 'College Savings',
            currency: {
              currencyCode: 'USD',
            },
            nickname: '529 for Kid',
            balanceType: BalanceTypeEnum.ASSET,
            availableCashBalance: 0,
            balanceAsOf: '2022-03-16T04:00:00Z',
            currentValue: 52672.49,
            marginBalance: 0,
            holdings: [
              {
                assetClasses: [
                  {
                    assetClass: AssetClass1Enum.DOMESTICBOND,
                    percent: 0,
                  }
                ],
                cashAccount: false,
                marketValue: 52672.49,
                positionType: PositionTypeEnum.LONG,
                purchasedPrice: 18.42,
                securityIdType: SecurityIdTypeEnum.ISIN,
                units: 2088.521,
                mutualFundSecurity: {
                  mutualFundType: MutualFundTypeEnum.OPENEND,
                  unitsStreet: 0,
                  unitsUser: 0,
                  reinvestDividends: true,
                  reinvestCapitalGains: true,
                  yield: 0,
                  yieldAsOfDate: '2019-08-24T14:15:22Z',
                },
              }
            ],
          },
        },
        {
          investmentAccount: {
          },
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
