/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  ArrayOfAccountPaymentNetworks,
  PaymentsController,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('PaymentsController', () => {
  let controller : PaymentsController;

  beforeAll(() => {
    controller = new PaymentsController(testClient);
  });

  it('should Test payment-networks', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const accountId = ':accountId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.paymentNetworks(
        version,
        providerId,
        accountId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ArrayOfAccountPaymentNetworks = {
      paymentNetworks: [
        {
          bankId: '125000024',
          identifier: '454992210071',
          identifierType: 'ACCOUNT_NUMBER',
          type: 'US_ACH',
          transferIn: true,
          transferOut: true,
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
