/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { StatementsController, XAkoyaInteractionTypeEnum } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('StatementsController', () => {
  let controller : StatementsController;

  beforeAll(() => {
    controller = new StatementsController(testClient);
  });

  it('should Test get-statement-list', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const startTime = '2020-03-30';

    const endTime = '2021-03-30';

    const offset = '0';

    const limit = 50;

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatementList(
        accountId,
        version,
        providerId,
        startTime,
        endTime,
        offset,
        limit,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-statements', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const statementId = 'statementId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatements(
        accountId,
        version,
        providerId,
        statementId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Accept: ['', false],
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/pdf', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-statements1', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const statementId = 'statementId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatements(
        accountId,
        version,
        providerId,
        statementId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Accept: ['', false],
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['image/gif', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-statements2', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const statementId = 'statementId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatements(
        accountId,
        version,
        providerId,
        statementId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Accept: ['', false],
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['image/jpeg', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-statements3', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const statementId = 'statementId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatements(
        accountId,
        version,
        providerId,
        statementId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Accept: ['', false],
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['image/tiff', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test get-statements4', async () => {
    const accountId = ':accountId';

    const version = 'v2';

    const providerId = 'mikomo';

    const statementId = 'statementId';

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const response = await makeApiCall(
      () => controller.getStatements(
        accountId,
        version,
        providerId,
        statementId,
        xAkoyaInteractionType
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      Accept: ['', false],
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['image/png', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
