/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  DebitCreditMemoEnum,
  ModeEnum,
  Status1Enum,
  TransactionsController,
  TransactionsEntity,
  TransactionTypeEnum,
  XAkoyaInteractionTypeEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('TransactionsController', () => {
  let controller : TransactionsController;

  beforeAll(() => {
    controller = new TransactionsController(testClient);
  });

  it('should Test get-transactions', async () => {
    const version = 'v2';

    const providerId = 'mikomo';

    const accountId = ':accountId';

    const startTime = '2020-03-30T04:00:00Z';

    const endTime = '2021-03-30T04:00:00Z';

    const offset = '0';

    const limit = 50;

    const xAkoyaInteractionType = XAkoyaInteractionTypeEnum.Batch;

    const mode = ModeEnum.Raw;

    const response = await makeApiCall(
      () => controller.getTransactions(
        version,
        providerId,
        accountId,
        startTime,
        endTime,
        offset,
        limit,
        xAkoyaInteractionType,
        mode
      )
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = {
      'x-akoya-interaction-id': ['', false],
      'Content-Type': ['application/json', true],
    };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: TransactionsEntity = {
      links: {
        prev: {
          href: '/transactions/v2/mikomo/33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d?endTime=2021-02-26T00%3A00%3A00Z&limit=5&offset=0&startTime=2019-02-26T00%3A00%3A00Z',
        },
      },
      transactions: [
        {
          depositTransaction: {
            accountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
            amount: 0.29,
            debitCreditMemo: DebitCreditMemoEnum.CREDIT,
            description: 'Interest Paid This Period',
            postedTimestamp: '2021-01-27T00:00:00Z',
            status: Status1Enum.POSTED,
            transactionId: '22ef95ee-6127-382d-a28c-5b8b7a15d2eb',
            transactionTimestamp: '2021-01-27T00:00:00Z',
            transactionType: TransactionTypeEnum.INTEREST,
          },
        },
        {
          depositTransaction: {
            accountId: '33fbd9e5-9cc3-3d7d-15b3-70d97d87ca1d',
            amount: 0.13,
            debitCreditMemo: DebitCreditMemoEnum.CREDIT,
            description: 'Interest Paid This Period',
            postedTimestamp: '2021-02-24T00:00:00Z',
            status: Status1Enum.POSTED,
            transactionId: 'f3fced9d-a7a2-4194-5a17-a2a9b09ff64a',
            transactionTimestamp: '2021-02-24T00:00:00Z',
            transactionType: TransactionTypeEnum.INTEREST,
          },
        }
      ],
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
