/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type TaxStatement1,
  type VersionEnum,
  type XAkoyaInteractionTypeEnum,
  type TypeDataTypeEnum,
  type AcceptEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { taxController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetTaxFormMCPToolRequest {
  'version': VersionEnum,
  'providerId': string,
  'taxFormId': string,
  'x-akoya-interaction-id': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
  'taxDataType': TypeDataTypeEnum,
  'Accept': AcceptEnum[],
}

async function executeGetTaxForm(
  req: GetTaxFormMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await taxController.getTaxForm(
      req['version'],
      req['providerId'],
      req['taxFormId'],
      req['x-akoya-interaction-id'],
      req['x-akoya-interaction-type'],
      req['taxDataType'],
      req['Accept']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetTaxForm(
  args: unknown | GetTaxFormMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Tax", "getTaxForm");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getTaxForm tool." }],
      isError: true,
    };
  }

  return await executeGetTaxForm(args as GetTaxFormMCPToolRequest);
}

export async function taxGetTaxFormTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "tax-getTaxForm",
      description: `Get the Tax Statement as JSON or PDF for a single tax document for the customer. Use [HTTP Accept request-header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) to specify desired content types. See \`AcceptHeader\` definition for typical values.

Not all providers support PDF payloads. See [this article](https://recipient.ddp.akoya.com/support/article/kA0Uw00000026VxKAI) in the Data Recipent Hub for a list of providers that support document PDFs.`,
      inputSchema: await schemas.loadSchema("Tax", "getTaxForm"),
    },
    handler: handleGetTaxForm,
  };
}

