/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type TaxStatementList,
  type VersionEnum,
  type XAkoyaInteractionTypeEnum,
  type AcceptEnum,
  type TypeFormTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { taxController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface TaxFormsSearchMCPToolRequest {
  'version': VersionEnum,
  'providerId': string,
  'x-akoya-interaction-id': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
  'Accept': AcceptEnum[],
  'taxYear': string,
  'taxForms': TypeFormTypeEnum[],
  'accountId': string,
}

async function executeTaxFormsSearch(
  req: TaxFormsSearchMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await taxController.taxFormsSearch(
      req['version'],
      req['providerId'],
      req['x-akoya-interaction-id'],
      req['x-akoya-interaction-type'],
      req['Accept'],
      req['taxYear'],
      req['taxForms'],
      req['accountId']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleTaxFormsSearch(
  args: unknown | TaxFormsSearchMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Tax", "taxFormsSearch");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for taxFormsSearch tool." }],
      isError: true,
    };
  }

  return await executeTaxFormsSearch(args as TaxFormsSearchMCPToolRequest);
}

export async function taxTaxFormsSearchTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "tax-taxFormsSearch",
      description: `Get the full lists of tax document data and tax form images available for a specific year for the current authorized customer.`,
      inputSchema: await schemas.loadSchema("Tax", "taxFormsSearch"),
    },
    handler: handleTaxFormsSearch,
  };
}

