/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type TransactionsEntity,
  type XAkoyaInteractionTypeEnum,
  type ModeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { transactionsController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetTransactionsMCPToolRequest {
  'version': string,
  'providerId': string,
  'accountId': string,
  'startTime': string,
  'endTime': string,
  'offset': string,
  'limit': number,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
  'mode': ModeEnum,
}

async function executeGetTransactions(
  req: GetTransactionsMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await transactionsController.getTransactions(
      req['version'],
      req['providerId'],
      req['accountId'],
      req['startTime'],
      req['endTime'],
      req['offset'],
      req['limit'],
      req['x-akoya-interaction-type'],
      req['mode']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetTransactions(
  args: unknown | GetTransactionsMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Transactions", "get-transactions");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getTransactions tool." }],
      isError: true,
    };
  }

  return await executeGetTransactions(args as GetTransactionsMCPToolRequest);
}

export async function transactionsGetTransactionsTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "transactions-getTransactions",
      description: `The transactions API allows you to retrieve transaction history of consumer-permissioned accounts.

> 🛑
> 
> The *id_token* should be used as the bearer token with this call.

For more information on how to paginate transaction results, please see: [Pagination](https://docs.akoya.com/v2/docs/pagination)

Use the \`mode\` query param to receive FDX-aligned, standardized data values (Beta). For example:

\`https://sandbox-products.ddp.akoya.com/transactions/v2/mikomo?mode=standard\`

\`mode\` is available in both sandbox and production.

\`mode\` is supported by a subset of providers. Log into the [Data Recipient Hub](https://recipient.ddp.akoya.com/login) and click [here](https://recipient.ddp.akoya.com/support/article/kA0Uw00000015GzKAI) to view a list of all providers supporting the \`mode\` parameter.`,
      inputSchema: await schemas.loadSchema("Transactions", "get-transactions"),
    },
    handler: handleGetTransactions,
  };
}

