/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type ArrayOfAccountPaymentNetworks,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { paymentsController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface PaymentNetworksMCPToolRequest {
  'version': string,
  'providerId': string,
  'accountId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
}

async function executePaymentNetworks(
  req: PaymentNetworksMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await paymentsController.paymentNetworks(
      req['version'],
      req['providerId'],
      req['accountId'],
      req['x-akoya-interaction-type']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handlePaymentNetworks(
  args: unknown | PaymentNetworksMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Payments", "payment-networks");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for paymentNetworks tool." }],
      isError: true,
    };
  }

  return await executePaymentNetworks(args as PaymentNetworksMCPToolRequest);
}

export async function paymentsPaymentNetworksTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "payments-paymentNetworks",
      description: `This product supports use cases such as payment enablement or account opening. The response includes identifiers necessary to make ACH and RTP payments. Identifiers include account number, routing number, identifier type (actual or tokenized account number), and payment network type such as ACH or RTP.

<br>

To see the response schema, select the \`200\` response below. For an example payload response, see the \`200\` example response below the *Try it* feature. 

> 🛑
> 
> The *id_token* should be used as the bearer token with this call.`,
      inputSchema: await schemas.loadSchema("Payments", "payment-networks"),
    },
    handler: handlePaymentNetworks,
  };
}

