/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { AcceptEnum, acceptEnumSchema } from '../models/acceptEnum';
import { TaxStatement1, taxStatement1Schema } from '../models/taxStatement1';
import {
  TaxStatementList,
  taxStatementListSchema,
} from '../models/taxStatementList';
import {
  TypeDataTypeEnum,
  typeDataTypeEnumSchema,
} from '../models/typeDataTypeEnum';
import {
  TypeFormTypeEnum,
  typeFormTypeEnumSchema,
} from '../models/typeFormTypeEnum';
import { VersionEnum, versionEnumSchema } from '../models/versionEnum';
import {
  XAkoyaInteractionTypeEnum,
  xAkoyaInteractionTypeEnumSchema,
} from '../models/xAkoyaInteractionTypeEnum';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';
import { ApiError } from '@apimatic/core';
import { CustomError } from '../errors/customError';

export class TaxController extends BaseController {
  /**
   * Get the full lists of tax document data and tax form images available for a specific year for the
   * current authorized customer.
   *
   * @param version                  Endpoint version.
   * @param providerId               Provider to query for Tax data.
   * @param xAkoyaInteractionId      Unique identifier to associate with this request. No
   *                                                              specific format required.
   * @param xAkoyaInteractionType    Identifies whether the customer is present (USER) or
   *                                                              it is a BATCH operation. Case-insensitive.
   * @param accept                   Use the [Accept HTTP request header](https:
   *                                                              //developer.mozilla.org/en-
   *                                                              US/docs/Web/HTTP/Headers/Accept) to indicate one or
   *                                                              more content types to request for the search result
   *                                                              response. Use `application/json` to request data or
   *                                                              `application/pdf to request images in comma-separated
   *                                                              array format.         Use in combination with
   *                                                              TaxDataTypeQuery parameter to request
   *                                                              `application/json` responses in ''JSON'' or
   *                                                              ''BASE64_PDF'' format for tax form data'
   * @param taxYear                  Tax year in which to search for tax forms.
   * @param taxForms                 One or more tax form type enums for the specific
   *                                                              documents being requested. Comma separated
   * @param accountId                Unique account identifier (not the account number)
   * @return Response from the API call
   */
  async taxFormsSearch(
    version: VersionEnum,
    providerId: string,
    xAkoyaInteractionId?: string,
    xAkoyaInteractionType?: XAkoyaInteractionTypeEnum,
    accept?: AcceptEnum[],
    taxYear?: string,
    taxForms?: TypeFormTypeEnum[],
    accountId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TaxStatementList>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      version: [version, versionEnumSchema],
      providerId: [providerId, string()],
      xAkoyaInteractionId: [xAkoyaInteractionId, optional(string())],
      xAkoyaInteractionType: [
        xAkoyaInteractionType,
        optional(xAkoyaInteractionTypeEnumSchema),
      ],
      accept: [accept, optional(array(acceptEnumSchema))],
      taxYear: [taxYear, optional(string())],
      taxForms: [taxForms, optional(array(typeFormTypeEnumSchema))],
      accountId: [accountId, optional(string())],
    });
    req.header('x-akoya-interaction-id', mapped.xAkoyaInteractionId);
    req.header('x-akoya-interaction-type', mapped.xAkoyaInteractionType);
    req.header('Accept', mapped.accept);
    req.query('taxYear', mapped.taxYear);
    req.query('taxForms', mapped.taxForms);
    req.query('accountId', mapped.accountId);
    req.appendTemplatePath`/tax-forms/${mapped.version}/${mapped.providerId}`;
    req.throwOn(400, CustomError, 'Bad Request');
    req.throwOn(404, CustomError, 'Not Found');
    req.throwOn(405, ApiError, 'Method Not Allowed');
    req.throwOn(406, ApiError, 'Not Acceptable');
    req.throwOn(
      408,
      CustomError,
      'Request timed out (round trip call took >10 seconds).'
    );
    req.throwOn(409, ApiError, 'Conflict');
    req.throwOn(500, CustomError, 'Internal Server Error');
    req.throwOn(
      501,
      CustomError,
      'FDX Version Not Supported or Not Implemented'
    );
    req.throwOn(503, CustomError, 'Scheduled Maintenance');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(taxStatementListSchema, requestOptions);
  }

  /**
   * Get the Tax Statement as JSON or PDF for a single tax document for the customer. Use [HTTP Accept
   * request-header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) to specify desired content
   * types. See `AcceptHeader` definition for typical values.
   *
   *
   *
   * Not all providers support PDF payloads. See [this article](https://recipient.ddp.akoya.
   * com/support/article/kA0Uw00000026VxKAI) in the Data Recipent Hub for a list of providers that
   * support document PDFs.
   *
   * @param version                  Endpoint version.
   * @param providerId               Provider to query for Tax data.
   * @param taxFormId                Unique identifier of the tax form to request.
   * @param xAkoyaInteractionId      Unique identifier to associate with this request. No
   *                                                              specific format required.
   * @param xAkoyaInteractionType    Identifies whether the customer is present (USER) or
   *                                                              it is a BATCH operation. Case-insensitive.
   * @param taxDataType              Use taxDataType to request `application/json` tax
   *                                                              form data response in 'JSON' or 'BASE64_PDF' format.
   *                                                              Omit if either format is acceptable. Used in
   *                                                              combination with AcceptHeader requesting
   *                                                              `application/json` response
   * @param accept                   Use the [Accept HTTP request header](https:
   *                                                              //developer.mozilla.org/en-
   *                                                              US/docs/Web/HTTP/Headers/Accept) to indicate one or
   *                                                              more content types to request for the search result
   *                                                              response. Use `application/json` to request data or
   *                                                              `application/pdf`to request images. In comma-
   *                                                              separated array format.         Use in combination
   *                                                              with TaxDataTypeQuery parameter to request
   *                                                              `application/json` responses in ''JSON'' or
   *                                                              ''BASE64_PDF'' format for tax form data'
   * @return Response from the API call
   */
  async getTaxForm(
    version: VersionEnum,
    providerId: string,
    taxFormId: string,
    xAkoyaInteractionId?: string,
    xAkoyaInteractionType?: XAkoyaInteractionTypeEnum,
    taxDataType?: TypeDataTypeEnum,
    accept?: AcceptEnum[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TaxStatement1>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      version: [version, versionEnumSchema],
      providerId: [providerId, string()],
      taxFormId: [taxFormId, string()],
      xAkoyaInteractionId: [xAkoyaInteractionId, optional(string())],
      xAkoyaInteractionType: [
        xAkoyaInteractionType,
        optional(xAkoyaInteractionTypeEnumSchema),
      ],
      taxDataType: [taxDataType, optional(typeDataTypeEnumSchema)],
      accept: [accept, optional(array(acceptEnumSchema))],
    });
    req.header('x-akoya-interaction-id', mapped.xAkoyaInteractionId);
    req.header('x-akoya-interaction-type', mapped.xAkoyaInteractionType);
    req.header('Accept', mapped.accept);
    req.query('taxDataType', mapped.taxDataType);
    req.appendTemplatePath`/tax-forms/${mapped.version}/${mapped.providerId}/${mapped.taxFormId}`;
    req.throwOn(
      400,
      CustomError,
      'Account ID is required for searching or validating authorization'
    );
    req.throwOn(
      404,
      CustomError,
      'Tax Form for provided Tax Form ID was not found'
    );
    req.throwOn(405, ApiError, 'Method Not Allowed');
    req.throwOn(406, CustomError, 'Content Type not Supported');
    req.throwOn(
      408,
      CustomError,
      'Request timed out (round trip call took >10 seconds).'
    );
    req.throwOn(
      409,
      CustomError,
      'Tax forms are not currently available for this account or this year'
    );
    req.throwOn(
      500,
      CustomError,
      'Catch-all exception where request was not processed due to an internal outage/issue.'
    );
    req.throwOn(501, CustomError, 'FdxVersion in header is not implemented.');
    req.throwOn(503, CustomError, 'System is down for maintenance.');
    req.authenticate([{ bearerAuth: true }]);
    return req.callAsJson(taxStatement1Schema, requestOptions);
  }
}
