/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type TaxlotsAccountIdHoldingIdResponse,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { investmentsController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetTaxlotsMCPToolRequest {
  'version': string,
  'providerId': string,
  'accountId': string,
  'holdingId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
  'offset': string,
  'limit': string,
}

async function executeGetTaxlots(
  req: GetTaxlotsMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await investmentsController.getTaxlots(
      req['version'],
      req['providerId'],
      req['accountId'],
      req['holdingId'],
      req['x-akoya-interaction-type'],
      req['offset'],
      req['limit']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetTaxlots(
  args: unknown | GetTaxlotsMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Investments", "get-taxlots");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getTaxlots tool." }],
      isError: true,
    };
  }

  return await executeGetTaxlots(args as GetTaxlotsMCPToolRequest);
}

export async function investmentsGetTaxlotsTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "investments-getTaxlots",
      description: `The taxlots API allows you to retrieve tax lots of consumer-permissioned accounts.

> 🛑
> 
> The *id_token* should be used as the bearer token with this call.`,
      inputSchema: await schemas.loadSchema("Investments", "get-taxlots"),
    },
    handler: handleGetTaxlots,
  };
}

