/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AccountInformationController,
  BalancesController,
  Client,
  CustomersController,
  Environment,
  InvestmentsController,
  PaymentsController,
  StatementsController,
  TaxController,
  TransactionsController,
  type Configuration,
} from 'akoya-apis-v-2-4-0-lib';

export const sdkClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.AKOYA_AP_IS_V_2_4_0_LIB_ENVIRONMENT;
  const timeout = process.env.AKOYA_AP_IS_V_2_4_0_LIB_TIMEOUT;
  const username = process.env.AKOYA_AP_IS_V_2_4_0_LIB_USERNAME;
  const password = process.env.AKOYA_AP_IS_V_2_4_0_LIB_PASSWORD;
  const accessToken = process.env.AKOYA_AP_IS_V_2_4_0_LIB_ACCESS_TOKEN;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (username !== undefined && password !== undefined) {
    config.basicAuthCredentials = { username: username, password: password };
  }

  if (accessToken !== undefined) {
    config.bearerAuthCredentials = { accessToken: accessToken };
  }

  return config;
}

export const accountInformationController = new AccountInformationController(sdkClient);
export const balancesController = new BalancesController(sdkClient);
export const customersController = new CustomersController(sdkClient);
export const investmentsController = new InvestmentsController(sdkClient);
export const paymentsController = new PaymentsController(sdkClient);
export const statementsController = new StatementsController(sdkClient);
export const taxController = new TaxController(sdkClient);
export const transactionsController = new TransactionsController(sdkClient);

