/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AcceptEnum
 */
export enum AcceptEnum {
  EnumApplicationjson = 'application/json',
  EnumApplicationpdf = 'application/pdf',
  EnumApplicationzip = 'application/zip',
  EnumImagegif = 'image/gif',
  EnumImagejpeg = 'image/jpeg',
  EnumImagepng = 'image/png',
  EnumImagetiff = 'image/tiff',
}

/**
 * Schema for AcceptEnum
 */
export const acceptEnumSchema: Schema<AcceptEnum> = stringEnum(AcceptEnum);
