/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LoanBalances, loanBalancesSchema } from './loanBalances';

export interface Account71 {
  /** Data elements included with balances specific to loan accounts */
  loanAccount?: LoanBalances;
}

export const account71Schema: Schema<Account71> = object({
  loanAccount: ['loanAccount', optional(lazy(() => loanBalancesSchema))],
});
