/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { InsuranceAccount, insuranceAccountSchema } from './insuranceAccount';

export interface Account4 {
  /** Insurance Account */
  insuranceAccount?: InsuranceAccount;
}

export const account4Schema: Schema<Account4> = object({
  insuranceAccount: [
    'insuranceAccount',
    optional(lazy(() => insuranceAccountSchema)),
  ],
});
