/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  LineOfCreditBalances,
  lineOfCreditBalancesSchema,
} from './lineOfCreditBalances';

export interface Account72 {
  /** Data elements included with balances specific to line of credit accounts */
  locAccount?: LineOfCreditBalances;
}

export const account72Schema: Schema<Account72> = object({
  locAccount: ['locAccount', optional(lazy(() => lineOfCreditBalancesSchema))],
});
