/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { DepositAccount, depositAccountSchema } from './depositAccount';

export interface Account {
  /** Deposit Account */
  depositAccount?: DepositAccount;
}

export const accountSchema: Schema<Account> = object({
  depositAccount: [
    'depositAccount',
    optional(lazy(() => depositAccountSchema)),
  ],
});
