/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  AccountHolderRelationshipEnum,
  accountHolderRelationshipEnumSchema,
} from './accountHolderRelationshipEnum';

export interface Account8 {
  /** Account ID of the related account */
  accountId?: string;
  /** Types of relationships between accounts and holders. Suggested values */
  relationship?: AccountHolderRelationshipEnum;
}

export const account8Schema: Schema<Account8> = object({
  accountId: ['accountId', optional(string())],
  relationship: ['relationship', optional(accountHolderRelationshipEnumSchema)],
});
