/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AnnuityBalances, annuityBalancesSchema } from './annuityBalances';

export interface Account75 {
  /** Data elements included with balances specific to annuity accounts */
  annuityAccount?: AnnuityBalances;
}

export const account75Schema: Schema<Account75> = object({
  annuityAccount: [
    'annuityAccount',
    optional(lazy(() => annuityBalancesSchema)),
  ],
});
