/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LoanAccount, loanAccountSchema } from './loanAccount';

export interface Account1 {
  /** Loan Account */
  loanAccount?: LoanAccount;
}

export const account1Schema: Schema<Account1> = object({
  loanAccount: ['loanAccount', optional(lazy(() => loanAccountSchema))],
});
