/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AccountCategoryEnum
 */
export enum AccountCategoryEnum {
  DEPOSITACCOUNT = 'DEPOSIT_ACCOUNT',
  INVESTMENTACCOUNT = 'INVESTMENT_ACCOUNT',
  LOANACCOUNT = 'LOAN_ACCOUNT',
  LOCACCOUNT = 'LOC_ACCOUNT',
  INSURANCEACCOUNT = 'INSURANCE_ACCOUNT',
}

/**
 * Schema for AccountCategoryEnum
 */
export const accountCategoryEnumSchema: Schema<AccountCategoryEnum> = stringEnum(
  AccountCategoryEnum
);
