/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountInformation,
  accountInformationSchema,
} from './accountInformation';

export interface Account2 {
  /** Line of Credit Account */
  locAccount?: AccountInformation;
}

export const account2Schema: Schema<Account2> = object({
  locAccount: ['locAccount', optional(lazy(() => accountInformationSchema))],
});
