/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  AccountHolderEntity,
  accountHolderEntitySchema,
} from './accountHolderEntity';

/** Contact information for the account */
export interface AccountContactEntity {
  /** Owners of the account */
  holders?: AccountHolderEntity[];
  /** Email addresses associated with the account */
  emails?: string[];
}

export const accountContactEntitySchema: Schema<AccountContactEntity> = object({
  holders: ['holders', optional(array(lazy(() => accountHolderEntitySchema)))],
  emails: ['emails', optional(array(string()))],
});
