/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InvestmentBalances,
  investmentBalancesSchema,
} from './investmentBalances';

export interface Account73 {
  /** Data elements included with balances specific to investment accounts */
  investmentAccount?: InvestmentBalances;
}

export const account73Schema: Schema<Account73> = object({
  investmentAccount: [
    'investmentAccount',
    optional(lazy(() => investmentBalancesSchema)),
  ],
});
