/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AnnuityAccount, annuityAccountSchema } from './annuityAccount';

export interface Account5 {
  /** Annuity Account */
  annuityAccount?: AnnuityAccount;
}

export const account5Schema: Schema<Account5> = object({
  annuityAccount: [
    'annuityAccount',
    optional(lazy(() => annuityAccountSchema)),
  ],
});
