/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountHolderRelationship2Enum,
  accountHolderRelationship2EnumSchema,
} from './accountHolderRelationship2Enum';
import { Customer1, customer1Schema } from './customer1';

/** Extends `Customer` and adds a `relationship` field to define the customer's relationship with an account */
export interface AccountHolderEntity {
  /** Represents a customer (end-user) */
  customer?: Customer1;
  /** Customer's relationship to the account */
  relationship?: AccountHolderRelationship2Enum;
}

export const accountHolderEntitySchema: Schema<AccountHolderEntity> = object({
  customer: ['customer', optional(lazy(() => customer1Schema))],
  relationship: [
    'relationship',
    optional(accountHolderRelationship2EnumSchema),
  ],
});
