/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AnnuityBalances, annuityBalancesSchema } from './annuityBalances';
import { DepositBalances, depositBalancesSchema } from './depositBalances';
import {
  InsuranceBalances,
  insuranceBalancesSchema,
} from './insuranceBalances';
import {
  InvestmentBalances,
  investmentBalancesSchema,
} from './investmentBalances';
import {
  LineOfCreditBalances,
  lineOfCreditBalancesSchema,
} from './lineOfCreditBalances';
import { LoanBalances, loanBalancesSchema } from './loanBalances';

export interface Account76 {
  /** Data elements included with balances specific to deposit accounts */
  depositAccount?: DepositBalances;
  /** Data elements included with balances specific to loan accounts */
  loanAccount?: LoanBalances;
  /** Data elements included with balances specific to line of credit accounts */
  locAccount?: LineOfCreditBalances;
  /** Data elements included with balances specific to investment accounts */
  investmentAccount?: InvestmentBalances;
  /** Data elements included with balances specific to insurance accounts */
  insuranceAccount?: InsuranceBalances;
  /** Data elements included with balances specific to annuity accounts */
  annuityAccount?: AnnuityBalances;
}

export const account76Schema: Schema<Account76> = object({
  depositAccount: [
    'depositAccount',
    optional(lazy(() => depositBalancesSchema)),
  ],
  loanAccount: ['loanAccount', optional(lazy(() => loanBalancesSchema))],
  locAccount: ['locAccount', optional(lazy(() => lineOfCreditBalancesSchema))],
  investmentAccount: [
    'investmentAccount',
    optional(lazy(() => investmentBalancesSchema)),
  ],
  insuranceAccount: [
    'insuranceAccount',
    optional(lazy(() => insuranceBalancesSchema)),
  ],
  annuityAccount: [
    'annuityAccount',
    optional(lazy(() => annuityBalancesSchema)),
  ],
});
