/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { DepositBalances, depositBalancesSchema } from './depositBalances';

export interface Account7 {
  /** Data elements included with balances specific to deposit accounts */
  depositAccount?: DepositBalances;
}

export const account7Schema: Schema<Account7> = object({
  depositAccount: [
    'depositAccount',
    optional(lazy(() => depositBalancesSchema)),
  ],
});
