/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InvestmentAccount,
  investmentAccountSchema,
} from './investmentAccount';

export interface Account3 {
  /** Investment Account */
  investmentAccount?: InvestmentAccount;
}

export const account3Schema: Schema<Account3> = object({
  investmentAccount: [
    'investmentAccount',
    optional(lazy(() => investmentAccountSchema)),
  ],
});
