/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AccountInformation,
  accountInformationSchema,
} from './accountInformation';
import { AnnuityAccount, annuityAccountSchema } from './annuityAccount';
import { DepositAccount, depositAccountSchema } from './depositAccount';
import { InsuranceAccount, insuranceAccountSchema } from './insuranceAccount';
import {
  InvestmentAccount,
  investmentAccountSchema,
} from './investmentAccount';
import { LoanAccount, loanAccountSchema } from './loanAccount';

export interface Account6 {
  /** Deposit Account */
  depositAccount?: DepositAccount;
  /** Loan Account */
  loanAccount?: LoanAccount;
  /** Line of Credit Account */
  locAccount?: AccountInformation;
  /** Investment Account */
  investmentAccount?: InvestmentAccount;
  /** Insurance Account */
  insuranceAccount?: InsuranceAccount;
  /** Annuity Account */
  annuityAccount?: AnnuityAccount;
}

export const account6Schema: Schema<Account6> = object({
  depositAccount: [
    'depositAccount',
    optional(lazy(() => depositAccountSchema)),
  ],
  loanAccount: ['loanAccount', optional(lazy(() => loanAccountSchema))],
  locAccount: ['locAccount', optional(lazy(() => accountInformationSchema))],
  investmentAccount: [
    'investmentAccount',
    optional(lazy(() => investmentAccountSchema)),
  ],
  insuranceAccount: [
    'insuranceAccount',
    optional(lazy(() => insuranceAccountSchema)),
  ],
  annuityAccount: [
    'annuityAccount',
    optional(lazy(() => annuityAccountSchema)),
  ],
});
