/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InvestmentAccountWithAllDetails,
  investmentAccountWithAllDetailsSchema,
} from './investmentAccountWithAllDetails';

export interface Account9 {
  /** Data elements included with the investment product */
  investmentAccount?: InvestmentAccountWithAllDetails;
}

export const account9Schema: Schema<Account9> = object({
  investmentAccount: [
    'investmentAccount',
    optional(lazy(() => investmentAccountWithAllDetailsSchema)),
  ],
});
