/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InsuranceBalances,
  insuranceBalancesSchema,
} from './insuranceBalances';

export interface Account74 {
  /** Data elements included with balances specific to insurance accounts */
  insuranceAccount?: InsuranceBalances;
}

export const account74Schema: Schema<Account74> = object({
  insuranceAccount: [
    'insuranceAccount',
    optional(lazy(() => insuranceBalancesSchema)),
  ],
});
