/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ActionEnum
 */
export enum ActionEnum {
  GET = 'GET',
  POST = 'POST',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  PUT = 'PUT',
}

/**
 * Schema for ActionEnum
 */
export const actionEnumSchema: Schema<ActionEnum> = stringEnum(ActionEnum);
