/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface Address2 {
  /** The location type of an address */
  type?: Type1Enum;
  /** May contain full address if not separated */
  line1?: string;
  line2?: string;
  line3?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  /** ISO 3166 Country Code */
  country?: string;
}

export const address2Schema: Schema<Address2> = object({
  type: ['type', optional(type1EnumSchema)],
  line1: ['line1', optional(string())],
  line2: ['line2', optional(string())],
  line3: ['line3', optional(string())],
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  postalCode: ['postalCode', optional(string())],
  country: ['country', optional(string())],
});
