/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ISO3166CountryCode2Enum,
  iSO3166CountryCode2EnumSchema,
} from './iSO3166CountryCode2Enum';

/** Box 1a, Physical address of property (street, city, state, ZIP code) */
export interface Address3 {
  /** Address line 1 */
  line1?: string;
  /** Address line 2 */
  line2?: string;
  /** Address line 3 */
  line3?: string;
  /** City */
  city?: string;
  /** State, Province, Territory, Canton or Prefecture. From [Universal Postal Union](https://www.upu.int/en/Postal-Solutions/Programmes-Services/Addressing-Solutions#addressing-s42-standard) as of 2-26-2020, [S42 International Address Standards](https://www.upu.int/UPU/media/upu/documents/PostCode/S42_International-Addressing-Standards.pdf). For U.S. addresses can be 2-character code from '#/components/schemas/StateCode' */
  region?: string;
  /** Postal code */
  postalCode?: string;
  /** Country code */
  country?: ISO3166CountryCode2Enum;
}

export const address3Schema: Schema<Address3> = object({
  line1: ['line1', optional(string())],
  line2: ['line2', optional(string())],
  line3: ['line3', optional(string())],
  city: ['city', optional(string())],
  region: ['region', optional(string())],
  postalCode: ['postalCode', optional(string())],
  country: ['country', optional(iSO3166CountryCode2EnumSchema)],
});
