/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  AkoyaAccountInfoProductAccounts,
  akoyaAccountInfoProductAccountsSchema,
} from './containers/akoyaAccountInfoProductAccounts';

export interface AkoyaAccountInfoProduct {
  /** An array of accounts with entity types dependent on the account type (deposit, investment, loan, line of credit, annuity or insurance) */
  accounts?: AkoyaAccountInfoProductAccounts[];
}

export const akoyaAccountInfoProductSchema: Schema<AkoyaAccountInfoProduct> = object(
  {
    accounts: [
      'accounts',
      optional(array(akoyaAccountInfoProductAccountsSchema)),
    ],
  }
);
