/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { AssetClass, assetClassSchema } from './assetClass';
import { CurrencyEntity, currencyEntitySchema } from './currencyEntity';
import {
  DebtSecurityEntity,
  debtSecurityEntitySchema,
} from './debtSecurityEntity';
import { FiAssetClass, fiAssetClassSchema } from './fiAssetClass';
import {
  FiAttributeEntity,
  fiAttributeEntitySchema,
} from './fiAttributeEntity';
import {
  HeldInAccountEnum,
  heldInAccountEnumSchema,
} from './heldInAccountEnum';
import {
  HoldingSubTypeEnum,
  holdingSubTypeEnumSchema,
} from './holdingSubTypeEnum';
import { HoldingTypeEnum, holdingTypeEnumSchema } from './holdingTypeEnum';
import { Inv401kSurceEnum, inv401kSurceEnumSchema } from './inv401kSurceEnum';
import {
  MutualFundSecurityEntity,
  mutualFundSecurityEntitySchema,
} from './mutualFundSecurityEntity';
import {
  OptionSecurityEntity,
  optionSecurityEntitySchema,
} from './optionSecurityEntity';
import {
  OtherSecurityEntity,
  otherSecurityEntitySchema,
} from './otherSecurityEntity';
import { PositionTypeEnum, positionTypeEnumSchema } from './positionTypeEnum';
import {
  SecurityIdTypeEnum,
  securityIdTypeEnumSchema,
} from './securityIdTypeEnum';
import {
  StockSecurityEntity,
  stockSecurityEntitySchema,
} from './stockSecurityEntity';
import {
  SweepSecurityEntity,
  sweepSecurityEntitySchema,
} from './sweepSecurityEntity';
import { TaxLot, taxLotSchema } from './taxLot';

export interface AnInvestmentHolding {
  /** Percent breakdown by asset class. */
  assetClasses?: AssetClass[];
  /** Cost is average of all purchases for holding. */
  averageCost?: boolean;
  /** If true, indicates that this holding is used to maintain proceeds from sales, dividends, and other cash postings to the investment account. */
  cashAccount?: boolean;
  /** Change in current price compared to previous day's close */
  changeInPrice?: number;
  /** Indicates the currency code used by the account. May also include currency rate. */
  currency?: CurrencyEntity;
  currentUnitPrice?: number;
  /** Current unit price as of date */
  currentUnitPriceDate?: string;
  /** Description of the holding */
  description?: string;
  /** For CDs, bonds, and other time-based holdings. */
  expirationDate?: string;
  /** Face value at the time of data retrieved. */
  faceValue?: number;
  /** Percent breakdown by FI-specific asset class percentage breakdown */
  fiAssetClasses?: FiAssetClass[];
  fiAttributes?: FiAttributeEntity[];
  /** Sub-account */
  heldInAccount?: HeldInAccountEnum;
  /** Long term persistent identity of the holding */
  holdingId?: string;
  /** Holding name or security name */
  holdingName?: string;
  holdingSubType?: HoldingSubTypeEnum;
  holdingType?: HoldingTypeEnum;
  /** Source for money for this security. */
  inv401kSurce?: Inv401kSurceEnum;
  /** Market value at the time of data retrieved */
  marketValue?: number;
  /** Date of original purchase */
  originalPurchaseDate?: string;
  positionType?: PositionTypeEnum;
  /** Price of holding at the time of purchase */
  purchasedPrice?: number;
  /** For CDs, bonds, and other rate based holdings. */
  rate?: number;
  /** Unique identifier of security */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdTypeEnum;
  /** Ticker / Market symbol */
  symbol?: string;
  /** Breakdown by tax lot. */
  taxLots?: TaxLot[];
  /** Number of shares (with decimals). */
  units?: number;
  /** Information about the mutual fund security specific to the type of security */
  mutualFundSecurity?: MutualFundSecurityEntity;
  /** Information about the option security specific to the type of security */
  optionSecurity?: OptionSecurityEntity;
  /** Information about the security specific to the type of security */
  otherSecurity?: OtherSecurityEntity;
  /** Information about the stock security specific to the type of security */
  stockSecurity?: StockSecurityEntity;
  /** Information about the sweep security specific to the type of security */
  sweepSecurity?: SweepSecurityEntity;
  /** Information about the debt security specific to the type of security */
  debtSecurity?: DebtSecurityEntity;
}

export const anInvestmentHoldingSchema: Schema<AnInvestmentHolding> = object({
  assetClasses: ['assetClasses', optional(array(lazy(() => assetClassSchema)))],
  averageCost: ['averageCost', optional(boolean())],
  cashAccount: ['cashAccount', optional(boolean())],
  changeInPrice: ['changeInPrice', optional(number())],
  currency: ['currency', optional(lazy(() => currencyEntitySchema))],
  currentUnitPrice: ['currentUnitPrice', optional(number())],
  currentUnitPriceDate: ['currentUnitPriceDate', optional(string())],
  description: ['description', optional(string())],
  expirationDate: ['expirationDate', optional(string())],
  faceValue: ['faceValue', optional(number())],
  fiAssetClasses: [
    'fiAssetClasses',
    optional(array(lazy(() => fiAssetClassSchema))),
  ],
  fiAttributes: [
    'fiAttributes',
    optional(array(lazy(() => fiAttributeEntitySchema))),
  ],
  heldInAccount: ['heldInAccount', optional(heldInAccountEnumSchema)],
  holdingId: ['holdingId', optional(string())],
  holdingName: ['holdingName', optional(string())],
  holdingSubType: ['holdingSubType', optional(holdingSubTypeEnumSchema)],
  holdingType: ['holdingType', optional(holdingTypeEnumSchema)],
  inv401kSurce: ['inv401kSurce', optional(inv401kSurceEnumSchema)],
  marketValue: ['marketValue', optional(number())],
  originalPurchaseDate: ['originalPurchaseDate', optional(string())],
  positionType: ['positionType', optional(positionTypeEnumSchema)],
  purchasedPrice: ['purchasedPrice', optional(number())],
  rate: ['rate', optional(number())],
  securityId: ['securityId', optional(string())],
  securityIdType: ['securityIdType', optional(securityIdTypeEnumSchema)],
  symbol: ['symbol', optional(string())],
  taxLots: ['taxLots', optional(array(lazy(() => taxLotSchema)))],
  units: ['units', optional(number())],
  mutualFundSecurity: [
    'mutualFundSecurity',
    optional(lazy(() => mutualFundSecurityEntitySchema)),
  ],
  optionSecurity: [
    'optionSecurity',
    optional(lazy(() => optionSecurityEntitySchema)),
  ],
  otherSecurity: [
    'otherSecurity',
    optional(lazy(() => otherSecurityEntitySchema)),
  ],
  stockSecurity: [
    'stockSecurity',
    optional(lazy(() => stockSecurityEntitySchema)),
  ],
  sweepSecurity: [
    'sweepSecurity',
    optional(lazy(() => sweepSecurityEntitySchema)),
  ],
  debtSecurity: [
    'debtSecurity',
    optional(lazy(() => debtSecurityEntitySchema)),
  ],
});
