/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnuityValueBasisEnum
 */
export enum AnnuityValueBasisEnum {
  FIXED = 'FIXED',
  VARIABLE = 'VARIABLE',
}

/**
 * Schema for AnnuityValueBasisEnum
 */
export const annuityValueBasisEnumSchema: Schema<AnnuityValueBasisEnum> = stringEnum(
  AnnuityValueBasisEnum
);
