/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnualIncreaseTypeEnum
 */
export enum AnnualIncreaseTypeEnum {
  FIXED = 'FIXED',
  PERCENT = 'PERCENT',
  DOLLAR = 'DOLLAR',
}

/**
 * Schema for AnnualIncreaseTypeEnum
 */
export const annualIncreaseTypeEnumSchema: Schema<AnnualIncreaseTypeEnum> = stringEnum(
  AnnualIncreaseTypeEnum
);
