/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AnnuityProductTypeEnum
 */
export enum AnnuityProductTypeEnum {
  CURRENCY = 'CURRENCY',
  SHARES = 'SHARES',
}

/**
 * Schema for AnnuityProductTypeEnum
 */
export const annuityProductTypeEnumSchema: Schema<AnnuityProductTypeEnum> = stringEnum(
  AnnuityProductTypeEnum
);
