/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  PaymentNetworkSupportedByAccount,
  paymentNetworkSupportedByAccountSchema,
} from './paymentNetworkSupportedByAccount';

export interface ArrayOfAccountPaymentNetworks {
  /** Array of payment networks */
  paymentNetworks?: PaymentNetworkSupportedByAccount[];
}

export const arrayOfAccountPaymentNetworksSchema: Schema<ArrayOfAccountPaymentNetworks> = object(
  {
    paymentNetworks: [
      'paymentNetworks',
      optional(array(lazy(() => paymentNetworkSupportedByAccountSchema))),
    ],
  }
);
