/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AssetClass1Enum
 */
export enum AssetClass1Enum {
  DOMESTICBOND = 'DOMESTICBOND',
  INTLBOND = 'INTLBOND',
  LARGESTOCK = 'LARGESTOCK',
  SMALLSTOCK = 'SMALLSTOCK',
  INTLSTOCK = 'INTLSTOCK',
  MONEYMARKET = 'MONEYMARKET',
  OTHER = 'OTHER',
}

/**
 * Schema for AssetClass1Enum
 */
export const assetClass1EnumSchema: Schema<AssetClass1Enum> = stringEnum(
  AssetClass1Enum
);
