/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { AssetClass1Enum, assetClass1EnumSchema } from './assetClass1Enum';

export interface AssetClass {
  assetClass?: AssetClass1Enum;
  /** Percentage of asset class that falls under this asset */
  percent?: number;
}

export const assetClassSchema: Schema<AssetClass> = object({
  assetClass: ['assetClass', optional(assetClass1EnumSchema)],
  percent: ['percent', optional(number())],
});
