/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  BalancesAccounts,
  balancesAccountsSchema,
} from './containers/balancesAccounts';

export interface Balances {
  /** An array of accounts with entity types dependent on the account type (deposit, investment, loan, line of credit, annuity or insurance) */
  accounts?: BalancesAccounts[];
}

export const balancesSchema: Schema<Balances> = object({
  accounts: ['accounts', optional(array(balancesAccountsSchema))],
});
