/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BalanceType1Enum
 */
export enum BalanceType1Enum {
  AMOUNT = 'AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
}

/**
 * Schema for BalanceType1Enum
 */
export const balanceType1EnumSchema: Schema<BalanceType1Enum> = stringEnum(
  BalanceType1Enum
);
