/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BalanceTypeEnum
 */
export enum BalanceTypeEnum {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
}

/**
 * Schema for BalanceTypeEnum
 */
export const balanceTypeEnumSchema: Schema<BalanceTypeEnum> = stringEnum(
  BalanceTypeEnum
);
