/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Name 1, Name 2 */
export interface BusinessName {
  /** Name line 1 */
  name1?: string;
  /** Name line 2 */
  name2?: string;
}

export const businessNameSchema: Schema<BusinessName> = object({
  name1: ['name1', optional(string())],
  name2: ['name2', optional(string())],
});
