/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CallTypeEnum
 */
export enum CallTypeEnum {
  CALL = 'CALL',
  PUT = 'PUT',
  PREFUND = 'PREFUND',
  MATURITY = 'MATURITY',
}

/**
 * Schema for CallTypeEnum
 */
export const callTypeEnumSchema: Schema<CallTypeEnum> = stringEnum(
  CallTypeEnum
);
