/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Code and amount pair used on IRS W-2, K-1, etc. */
export interface CodeAndAmount {
  /** Code */
  code?: string;
  /** Amount */
  amount?: number;
}

export const codeAndAmountSchema: Schema<CodeAndAmount> = object({
  code: ['code', optional(string())],
  amount: ['amount', optional(number())],
});
