/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CompoundingPeriodEnum
 */
export enum CompoundingPeriodEnum {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  SEMIMONTHLY = 'SEMIMONTHLY',
  MONTHLY = 'MONTHLY',
  SEMIANNUALLY = 'SEMIANNUALLY',
  ANNUALLY = 'ANNUALLY',
}

/**
 * Schema for CompoundingPeriodEnum
 */
export const compoundingPeriodEnumSchema: Schema<CompoundingPeriodEnum> = stringEnum(
  CompoundingPeriodEnum
);
