/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CouponMatureFrequencyEnum
 */
export enum CouponMatureFrequencyEnum {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMIANNUAL = 'SEMIANNUAL',
  ANNUAL = 'ANNUAL',
  OTHER = 'OTHER',
}

/**
 * Schema for CouponMatureFrequencyEnum
 */
export const couponMatureFrequencyEnumSchema: Schema<CouponMatureFrequencyEnum> = stringEnum(
  CouponMatureFrequencyEnum
);
