/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Customer2, customer2Schema } from './customer2';

/** Currently authenticated end-user */
export interface CurrentCustomer {
  /** current customer */
  customer?: Customer2;
}

export const currentCustomerSchema: Schema<CurrentCustomer> = object({
  customer: ['customer', optional(lazy(() => customer2Schema))],
});
