/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Customer1, customer1Schema } from './customer1';

/** Represents a customer (end-user) */
export interface Customer {
  /** Represents a customer (end-user) */
  customer?: Customer1;
}

export const customerSchema: Schema<Customer> = object({
  customer: ['customer', optional(lazy(() => customer1Schema))],
});
