/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { Account8, account8Schema } from './account8';
import { Address2, address2Schema } from './address2';
import { Name, nameSchema } from './name';
import { Telephone, telephoneSchema } from './telephone';

/** Represents a customer (end-user) */
export interface Customer1 {
  /** Long-term persistent identity of the end-user. This identity must be unique to the owning institution */
  customerId?: string;
  /** The end-user's name */
  name?: Name;
  /** An array of the end-user's physical mail addresses */
  addresses?: Address2[];
  telephones?: Telephone[];
  /** An array of the end-user's electronic mail addresses */
  email?: string[];
  /** List of accounts related to this end-user */
  accounts?: Account8[];
}

export const customer1Schema: Schema<Customer1> = object({
  customerId: ['customerId', optional(string())],
  name: ['name', optional(lazy(() => nameSchema))],
  addresses: ['addresses', optional(array(lazy(() => address2Schema)))],
  telephones: ['telephones', optional(array(lazy(() => telephoneSchema)))],
  email: ['email', optional(array(string()))],
  accounts: ['accounts', optional(array(lazy(() => account8Schema)))],
});
