/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Date, description, and amount. When used in 1098-Q, description is optional */
export interface DateAndAmount {
  /** Date of amount. When used in 1098-Q, date of last payment in month */
  date?: string;
  /** Description of amount. When used in 1098-Q, may use MonthAbbreviation */
  description?: string;
  /** Amount of payment or receipt. When used in 1098-Q, monthly total */
  amount?: number;
}

export const dateAndAmountSchema: Schema<DateAndAmount> = object({
  date: ['date', optional(string())],
  description: ['description', optional(string())],
  amount: ['amount', optional(number())],
});
