/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebitCreditMemoEnum
 */
export enum DebitCreditMemoEnum {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

/**
 * Schema for DebitCreditMemoEnum
 */
export const debitCreditMemoEnumSchema: Schema<DebitCreditMemoEnum> = stringEnum(
  DebitCreditMemoEnum
);
