/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebtTypeEnum
 */
export enum DebtTypeEnum {
  ASSET = 'ASSET',
  COUPON = 'COUPON',
}

/**
 * Schema for DebtTypeEnum
 */
export const debtTypeEnumSchema: Schema<DebtTypeEnum> = stringEnum(
  DebtTypeEnum
);
