/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { CallTypeEnum, callTypeEnumSchema } from './callTypeEnum';
import {
  CouponMatureFrequencyEnum,
  couponMatureFrequencyEnumSchema,
} from './couponMatureFrequencyEnum';
import { DebtClassEnum, debtClassEnumSchema } from './debtClassEnum';
import { DebtTypeEnum, debtTypeEnumSchema } from './debtTypeEnum';

/** Information about the debt security specific to the type of security */
export interface DebtSecurityEntity {
  /** Par value amount */
  parValue?: number;
  /** Debt type */
  debtType?: DebtTypeEnum;
  /** Classification of debt */
  debtClass?: DebtClassEnum;
  /** Bond coupon rate for next closest call date */
  couponRate?: number;
  /** Maturity date for next coupon */
  couponDate?: string;
  /** When coupons mature */
  couponMatureFrequency?: CouponMatureFrequencyEnum;
  /** Bond call price */
  callPrice?: number;
  /** Yield to next call */
  yieldToCall?: number;
  /** Next call date */
  callDate?: string;
  /** Type of next call */
  callType?: CallTypeEnum;
  /** Yield to maturity */
  yieldToMaturity?: number;
  /** Bond Maturity date */
  bondMaturityDate?: string;
}

export const debtSecurityEntitySchema: Schema<DebtSecurityEntity> = object({
  parValue: ['parValue', optional(number())],
  debtType: ['debtType', optional(debtTypeEnumSchema)],
  debtClass: ['debtClass', optional(debtClassEnumSchema)],
  couponRate: ['couponRate', optional(number())],
  couponDate: ['couponDate', optional(string())],
  couponMatureFrequency: [
    'couponMatureFrequency',
    optional(couponMatureFrequencyEnumSchema),
  ],
  callPrice: ['callPrice', optional(number())],
  yieldToCall: ['yieldToCall', optional(number())],
  callDate: ['callDate', optional(string())],
  callType: ['callType', optional(callTypeEnumSchema)],
  yieldToMaturity: ['yieldToMaturity', optional(number())],
  bondMaturityDate: ['bondMaturityDate', optional(string())],
});
