/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DebtClassEnum
 */
export enum DebtClassEnum {
  TREASURY = 'TREASURY',
  MUNICIPAL = 'MUNICIPAL',
  CORPORATE = 'CORPORATE',
  OTHER = 'OTHER',
}

/**
 * Schema for DebtClassEnum
 */
export const debtClassEnumSchema: Schema<DebtClassEnum> = stringEnum(
  DebtClassEnum
);
