/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface DeliveryAddress {
  /** Type of address location. One of BUSINESS, HOME, MAILING */
  type?: string;
}

export const deliveryAddressSchema: Schema<DeliveryAddress> = object({
  type: ['type', optional(string())],
});
