/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Description and amount pair used on IRS W-2, etc. */
export interface DescriptionAndAmount {
  /** Description */
  description?: string;
  /** Amount */
  amount?: number;
}

export const descriptionAndAmountSchema: Schema<DescriptionAndAmount> = object({
  description: ['description', optional(string())],
  amount: ['amount', optional(number())],
});
