/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The country and region of the business customer's location */
export interface Domicile {
  region?: string;
  country?: string;
}

export const domicileSchema: Schema<Domicile> = object({
  region: ['region', optional(string())],
  country: ['country', optional(string())],
});
