/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Vesting, vestingSchema } from './vesting';

export interface EquityGrant {
  /** Unique identifier of grant */
  grantId?: string;
  /** Date grant was given */
  grantDate?: string;
  /** Type of grant */
  grantType?: string;
  seqNum?: number;
  /** Grant price */
  grantPrice?: number;
  /** Indicates the currency of grant USD vs AUD vs EUR etc (for share awards, you will still get a USD) */
  grantCurrencyCode?: string;
  /** Number of options */
  quantityGranted?: number;
  quantityOutstanding?: number;
  /** Date grant expires */
  expirationDate?: string;
  /** An array of equityGrant vestings. Provides the past, present, and future vesting schedule and percentages. */
  vestings?: Vesting[];
}

export const equityGrantSchema: Schema<EquityGrant> = object({
  grantId: ['grantId', optional(string())],
  grantDate: ['grantDate', optional(string())],
  grantType: ['grantType', optional(string())],
  seqNum: ['seqNum', optional(number())],
  grantPrice: ['grantPrice', optional(number())],
  grantCurrencyCode: ['grantCurrencyCode', optional(string())],
  quantityGranted: ['quantityGranted', optional(number())],
  quantityOutstanding: ['quantityOutstanding', optional(number())],
  expirationDate: ['expirationDate', optional(string())],
  vestings: ['vestings', optional(array(lazy(() => vestingSchema)))],
});
