/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExpiredOptionTypeEnum
 */
export enum ExpiredOptionTypeEnum {
  GRANTED = 'GRANTED',
  PURCHASED = 'PURCHASED',
}

/**
 * Schema for ExpiredOptionTypeEnum
 */
export const expiredOptionTypeEnumSchema: Schema<ExpiredOptionTypeEnum> = stringEnum(
  ExpiredOptionTypeEnum
);
