/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ExpiredOptionType1Enum
 */
export enum ExpiredOptionType1Enum {
  GRANTED = 'GRANTED',
  PURCHASED = 'PURCHASED',
}

/**
 * Schema for ExpiredOptionType1Enum
 */
export const expiredOptionType1EnumSchema: Schema<ExpiredOptionType1Enum> = stringEnum(
  ExpiredOptionType1Enum
);
