/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface FiAssetClass {
  /** FI-specific asset class */
  assetClass?: string;
  /** Percentage of asset class that falls under this asset */
  percent?: number;
}

export const fiAssetClassSchema: Schema<FiAssetClass> = object({
  assetClass: ['assetClass', optional(string())],
  percent: ['percent', optional(number())],
});
