/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Data provider-specific attribute */
export interface FiAttributeEntity {
  /** Name of attribute */
  name?: string;
  /** Value of attribute */
  value?: string;
}

export const fiAttributeEntitySchema: Schema<FiAttributeEntity> = object({
  name: ['name', optional(string())],
  value: ['value', optional(string())],
});
