/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  HealthInsuranceCoverage,
  healthInsuranceCoverageSchema,
} from './healthInsuranceCoverage';
import {
  HealthInsuranceMarketplaceCoveredIndividual,
  healthInsuranceMarketplaceCoveredIndividualSchema,
} from './healthInsuranceMarketplaceCoveredIndividual';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Health Insurance Marketplace Statement */
export interface Form1095A2 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Box 1, Marketplace identifier */
  marketplaceId?: string;
  /** Box 2, Marketplace-assigned policy number */
  marketplacePolicyNumber?: string;
  /** Box 3, Policy issuer's name */
  policyIssuerName?: string;
  /** Box 6, Recipient's date of birth */
  recipientDateOfBirth?: string;
  /** Box 7, Recipient's spouse's name */
  spouseName?: string;
  /** Box 8, Recipient's spouse's SSN */
  spouseTin?: string;
  /** Box 9, Recipient's spouse's date of birth */
  spouseDateOfBirth?: string;
  /** Box 10, Policy start date */
  policyStartDate?: string;
  /** Box 11, Policy termination date */
  policyTerminationDate?: string;
  /** Boxes 16+, Covered Individuals */
  coveredIndividuals?: HealthInsuranceMarketplaceCoveredIndividual[];
  /** Boxes 21-33, Coverage Information */
  coverages?: HealthInsuranceCoverage[];
}

export const form1095A2Schema: Schema<Form1095A2> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  marketplaceId: ['marketplaceId', optional(string())],
  marketplacePolicyNumber: ['marketplacePolicyNumber', optional(string())],
  policyIssuerName: ['policyIssuerName', optional(string())],
  recipientDateOfBirth: ['recipientDateOfBirth', optional(string())],
  spouseName: ['spouseName', optional(string())],
  spouseTin: ['spouseTin', optional(string())],
  spouseDateOfBirth: ['spouseDateOfBirth', optional(string())],
  policyStartDate: ['policyStartDate', optional(string())],
  policyTerminationDate: ['policyTerminationDate', optional(string())],
  coveredIndividuals: [
    'coveredIndividuals',
    optional(
      array(lazy(() => healthInsuranceMarketplaceCoveredIndividualSchema))
    ),
  ],
  coverages: [
    'coverages',
    optional(array(lazy(() => healthInsuranceCoverageSchema))),
  ],
});
