/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Certain Government Payments */
export interface Form1099G2 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Unemployment compensation */
  unemploymentCompensation?: number;
  /** Box 2, State or local income tax refunds, credits, or offsets */
  taxRefund?: number;
  /** Box 3, Box 2 amount is for tax year */
  refundYear?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, RTAA payments */
  rtaaPayments?: number;
  /** Box 6, Taxable grants */
  grants?: number;
  /** Box 7, Agriculture payments */
  agriculturePayments?: number;
  /** Box 8, If checked, box 2 is trade or business income */
  businessIncome?: boolean;
  /** Box 9, Market gain */
  marketGain?: number;
  /** Boxes 10-11, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
}

export const form1099G2Schema: Schema<Form1099G2> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  accountNumber: ['accountNumber', optional(string())],
  unemploymentCompensation: ['unemploymentCompensation', optional(number())],
  taxRefund: ['taxRefund', optional(number())],
  refundYear: ['refundYear', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  rtaaPayments: ['rtaaPayments', optional(number())],
  grants: ['grants', optional(number())],
  agriculturePayments: ['agriculturePayments', optional(number())],
  businessIncome: ['businessIncome', optional(boolean())],
  marketGain: ['marketGain', optional(number())],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
});
