/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Miscellaneous Income, from PAYER (1st-2nd boxes as issuer) to RECIPIENT (3rd-4th boxes) */
export interface Form1099MISC {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Rents */
  rents?: number;
  /** Box 2, Royalties */
  royalties?: number;
  /** Box 3, Other income */
  otherIncome?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Fishing boat proceeds */
  fishingBoatProceeds?: number;
  /** Box 6, Medical and health care payments */
  medicalHealthPayment?: number;
  /** Box 7, Payer made direct sales of $5,000 or more of consumer products to a buyer (recipient) for resale */
  payerDirectSales?: boolean;
  /** Box 8, Substitute payments in lieu of dividends or interest */
  substitutePayments?: number;
  /** Box 9, Crop insurance proceeds */
  cropInsurance?: number;
  /** Second TIN Notice */
  secondTinNotice?: boolean;
  /** Box 10, Gross proceeds paid to an attorney */
  grossAttorney?: number;
  /** Box 11, Fish purchased for resale */
  fishPurchased?: number;
  /** Box 12, Section 409A deferrals */
  section409ADeferrals?: number;
  /** Box 13, FATCA filing requirement */
  foreignAccountTaxCompliance?: boolean;
  /** Box 14, Excess golden parachute payments */
  excessGolden?: number;
  /** Box 15, Nonqualified Deferred Compensation */
  nonQualifiedDeferredCompensation?: number;
  /** Boxes 16-18, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
}

export const form1099MISCSchema: Schema<Form1099MISC> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  accountNumber: ['accountNumber', optional(string())],
  rents: ['rents', optional(number())],
  royalties: ['royalties', optional(number())],
  otherIncome: ['otherIncome', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  fishingBoatProceeds: ['fishingBoatProceeds', optional(number())],
  medicalHealthPayment: ['medicalHealthPayment', optional(number())],
  payerDirectSales: ['payerDirectSales', optional(boolean())],
  substitutePayments: ['substitutePayments', optional(number())],
  cropInsurance: ['cropInsurance', optional(number())],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
  grossAttorney: ['grossAttorney', optional(number())],
  fishPurchased: ['fishPurchased', optional(number())],
  section409ADeferrals: ['section409ADeferrals', optional(number())],
  foreignAccountTaxCompliance: [
    'foreignAccountTaxCompliance',
    optional(boolean()),
  ],
  excessGolden: ['excessGolden', optional(number())],
  nonQualifiedDeferredCompensation: [
    'nonQualifiedDeferredCompensation',
    optional(number()),
  ],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
});
