/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Interest Income */
export interface Form1099INT2 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** FATCA filing requirement */
  foreignAccountTaxCompliance?: boolean;
  /** Account number */
  accountNumber?: string;
  /** Payer's RTN */
  payerRtn?: string;
  /** Box 1, Interest income */
  interestIncome?: number;
  /** Box 2, Early withdrawal penalty */
  earlyWithdrawalPenalty?: number;
  /** Box 3, Interest on U.S. Savings Bonds and Treasury obligations */
  usBondInterest?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Investment expenses */
  investmentExpenses?: number;
  /** Box 6, Foreign tax paid */
  foreignTaxPaid?: number;
  /** Box 7, Foreign country or U.S. possession */
  foreignCountry?: string;
  /** Box 8, Tax-exempt interest */
  taxExemptInterest?: number;
  /** Box 9, Specified private activity bond interest */
  specifiedPabInterest?: number;
  /** Box 10, Market discount */
  marketDiscount?: number;
  /** Box 11, Bond premium */
  bondPremium?: number;
  /** Box 12, Bond premium on Treasury obligations */
  usBondPremium?: number;
  /** Box 13, Bond premium on tax-exempt bond */
  taxExemptBondPremium?: number;
  /** Box 14, Tax-exempt bond CUSIP no. */
  cusipNumber?: string;
  /** Boxes 15-17, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Supplemental foreign income amount information (description is country) */
  foreignIncomes?: DescriptionAndAmount[];
  /** Supplemental tax-exempt income by state (description is state) */
  stateTaxExemptIncome?: DescriptionAndAmount[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
}

export const form1099INT2Schema: Schema<Form1099INT2> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  foreignAccountTaxCompliance: [
    'foreignAccountTaxCompliance',
    optional(boolean()),
  ],
  accountNumber: ['accountNumber', optional(string())],
  payerRtn: ['payerRtn', optional(string())],
  interestIncome: ['interestIncome', optional(number())],
  earlyWithdrawalPenalty: ['earlyWithdrawalPenalty', optional(number())],
  usBondInterest: ['usBondInterest', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  investmentExpenses: ['investmentExpenses', optional(number())],
  foreignTaxPaid: ['foreignTaxPaid', optional(number())],
  foreignCountry: ['foreignCountry', optional(string())],
  taxExemptInterest: ['taxExemptInterest', optional(number())],
  specifiedPabInterest: ['specifiedPabInterest', optional(number())],
  marketDiscount: ['marketDiscount', optional(number())],
  bondPremium: ['bondPremium', optional(number())],
  usBondPremium: ['usBondPremium', optional(number())],
  taxExemptBondPremium: ['taxExemptBondPremium', optional(number())],
  cusipNumber: ['cusipNumber', optional(string())],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
  foreignIncomes: [
    'foreignIncomes',
    optional(array(lazy(() => descriptionAndAmountSchema))),
  ],
  stateTaxExemptIncome: [
    'stateTaxExemptIncome',
    optional(array(lazy(() => descriptionAndAmountSchema))),
  ],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
});
