/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** HSA, Archer MSA, or Medicare Advantage MSA Information */
export interface Form5498SA2 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Account number */
  accountNumber?: string;
  /** Box 1, Employee or self-employed person's Archer MSA contributions made in current and following years for current year */
  msaContributions?: number;
  /** Box 2, Total contributions made in current year */
  totalContributions?: number;
  /** Box 3, Total HSA or Archer MSA contributions made in following year for current year */
  totalPostYearEnd?: number;
  /** Box 4, Rollover contributions */
  rolloverContributions?: number;
  /** Box 5, Fair market value of HSA, Archer MSA, or Medicare Advantage (MA) MSA */
  fairMarketValue?: number;
  /** Box 6a, HSA */
  hsa?: boolean;
  /** Box 6b, Archer MSA */
  archer?: boolean;
  /** Box 6c, Medicare Advantage (MA) MSA */
  maMsa?: boolean;
}

export const form5498SA2Schema: Schema<Form5498SA2> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  accountNumber: ['accountNumber', optional(string())],
  msaContributions: ['msaContributions', optional(number())],
  totalContributions: ['totalContributions', optional(number())],
  totalPostYearEnd: ['totalPostYearEnd', optional(number())],
  rolloverContributions: ['rolloverContributions', optional(number())],
  fairMarketValue: ['fairMarketValue', optional(number())],
  hsa: ['hsa', optional(boolean())],
  archer: ['archer', optional(boolean())],
  maMsa: ['maMsa', optional(boolean())],
});
