/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Original Issue Discount, from PAYER (1st-2nd boxes as issuer) to RECIPIENT (3rd-4th boxes) */
export interface Form1099OID {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** FATCA filing requirement */
  foreignAccountTaxCompliance?: boolean;
  /** Account number */
  accountNumber?: string;
  /** Box 1, Original issue discount */
  originalIssueDiscount?: number;
  /** Box 2, Other periodic interest */
  otherPeriodicInterest?: number;
  /** Box 3, Early withdrawal penalty */
  earlyWithdrawalPenalty?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Market discount */
  marketDiscount?: number;
  /** Box 6, Acquisition premium */
  acquisitionPremium?: number;
  /** Box 7, Description */
  oidDescription?: string;
  /** Box 8, Original issue discount on U.S. Treasury obligations */
  discountOnTreasuryObligations?: number;
  /** Box 9, Investment expenses */
  investmentExpenses?: number;
  /** Box 10, Bond premium */
  bondPremium?: number;
  /** Box 11, Tax-exempt OID */
  taxExemptOid?: number;
  /** Boxes 12-14, State and Local tax withheld */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Supplemental: State name and tax-exempt OID by state */
  stateExemptOid?: DescriptionAndAmount[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
}

export const form1099OIDSchema: Schema<Form1099OID> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  foreignAccountTaxCompliance: [
    'foreignAccountTaxCompliance',
    optional(boolean()),
  ],
  accountNumber: ['accountNumber', optional(string())],
  originalIssueDiscount: ['originalIssueDiscount', optional(number())],
  otherPeriodicInterest: ['otherPeriodicInterest', optional(number())],
  earlyWithdrawalPenalty: ['earlyWithdrawalPenalty', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  marketDiscount: ['marketDiscount', optional(number())],
  acquisitionPremium: ['acquisitionPremium', optional(number())],
  oidDescription: ['oidDescription', optional(string())],
  discountOnTreasuryObligations: [
    'discountOnTreasuryObligations',
    optional(number()),
  ],
  investmentExpenses: ['investmentExpenses', optional(number())],
  bondPremium: ['bondPremium', optional(number())],
  taxExemptOid: ['taxExemptOid', optional(number())],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
  stateExemptOid: [
    'stateExemptOid',
    optional(array(lazy(() => descriptionAndAmountSchema))),
  ],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
});
