/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { MonthAndAmount, monthAndAmountSchema } from './monthAndAmount';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TelephoneNumberPlusExtension2,
  telephoneNumberPlusExtension2Schema,
} from './telephoneNumberPlusExtension2';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Merchant Card and Third-Party Network Payments */
export interface Form1099K2 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Check to indicate if FILER is a Payment Settlement Entity (PSE) */
  paymentSettlementEntity?: boolean;
  /** Check to indicate if FILER is an Electronic Payment Facilitator (EPF) / Other third party */
  electronicPaymentFacilitator?: boolean;
  /** Check to indicate transactions reported are: Payment card */
  paymentCard?: boolean;
  /** Check to indicate transactions reported are: Third party network */
  thirdPartyNetwork?: boolean;
  /** PSE's name */
  pseName?: string;
  /** PSE's phone number */
  psePhone?: TelephoneNumberPlusExtension2;
  /** Account number */
  accountNumber?: string;
  /** Box 1a, Gross amount of payment card/third party network transactions */
  grossAmount?: number;
  /** Box 1b, Card Not Present Transactions */
  cardNotPresent?: number;
  /** Box 2, Merchant category code */
  merchantCategoryCode?: string;
  /** Box 3, Number of purchase transactions */
  numberOfTransactions?: number;
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 5, Monthly amounts */
  monthAmounts?: MonthAndAmount[];
  /** Boxes 6-8, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
}

export const form1099K2Schema: Schema<Form1099K2> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  paymentSettlementEntity: ['paymentSettlementEntity', optional(boolean())],
  electronicPaymentFacilitator: [
    'electronicPaymentFacilitator',
    optional(boolean()),
  ],
  paymentCard: ['paymentCard', optional(boolean())],
  thirdPartyNetwork: ['thirdPartyNetwork', optional(boolean())],
  pseName: ['pseName', optional(string())],
  psePhone: [
    'psePhone',
    optional(lazy(() => telephoneNumberPlusExtension2Schema)),
  ],
  accountNumber: ['accountNumber', optional(string())],
  grossAmount: ['grossAmount', optional(number())],
  cardNotPresent: ['cardNotPresent', optional(number())],
  merchantCategoryCode: ['merchantCategoryCode', optional(string())],
  numberOfTransactions: ['numberOfTransactions', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  monthAmounts: [
    'monthAmounts',
    optional(array(lazy(() => monthAndAmountSchema))),
  ],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
});
