/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { MonthAndAmount, monthAndAmountSchema } from './monthAndAmount';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Bond Tax Credit, from FORM 1097-BTC ISSUER (1st-2nd boxes) to RECIPIENT (3rd-6th boxes) */
export interface Form1097BTC {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Form 1097-BTC issuer is: Issuer of bond or its agent filing current year Form 1097-BTC for credit being reported */
  filingForCredit?: boolean;
  /** Form 1097-BTC issuer is: An entity or a person that received or should have received a current year Form 1097-BTC and is distributing part or all of that credit to others */
  asNominee?: boolean;
  /** Box 1, Total */
  total?: number;
  /** Box 2a, Code */
  bondCode?: string;
  /** Box 2b, Unique Identifier */
  uniqueId?: string;
  /** Box 3, Bond type */
  bondType?: string;
  /** Box 5, Amounts by month */
  amounts?: MonthAndAmount[];
  /** Box 6, Comments */
  comments?: string;
}

export const form1097BTCSchema: Schema<Form1097BTC> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  filingForCredit: ['filingForCredit', optional(boolean())],
  asNominee: ['asNominee', optional(boolean())],
  total: ['total', optional(number())],
  bondCode: ['bondCode', optional(string())],
  uniqueId: ['uniqueId', optional(string())],
  bondType: ['bondType', optional(string())],
  amounts: ['amounts', optional(array(lazy(() => monthAndAmountSchema)))],
  comments: ['comments', optional(string())],
});
