/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { MonthAndAmount, monthAndAmountSchema } from './monthAndAmount';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Health Coverage Tax Credit (HCTC) Advance Payments, from ISSUER/PROVIDER (1st-2nd boxes as issuer) to RECIPIENT (3rd-4th boxes) */
export interface Form1099H {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Box 1, Amount of HCTC advance payments */
  advancePayments?: number;
  /** Box 2, Number of months HCTC advance payments and reimbursement credits paid to you */
  numberOfMonths?: number;
  /** Boxes 3-14, Payments by month */
  payments?: MonthAndAmount[];
}

export const form1099HSchema: Schema<Form1099H> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  advancePayments: ['advancePayments', optional(number())],
  numberOfMonths: ['numberOfMonths', optional(number())],
  payments: ['payments', optional(array(lazy(() => monthAndAmountSchema)))],
});
