/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  SecurityDetailIRSForm1099B,
  securityDetailIRSForm1099BSchema,
} from './securityDetailIRSForm1099B';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Proceeds From Broker and Barter Exchange Transactions, from PAYER (1st-2nd boxes as issuer) to RECIPIENT (3rd-6th boxes) */
export interface Form1099B {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Account number */
  accountNumber?: string;
  /** Boxes 14-16, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
  /** Box 4, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 8, Profit or (loss) realized in current year on closed contracts */
  profitOnClosedContracts?: number;
  /** Box 9, Unrealized profit or loss on open contracts at end of last year */
  unrealizedProfitOpenContractsBegin?: number;
  /** Box 10, Unrealized profit or loss on open contracts at end of current year */
  unrealizedProfitOpenContractsEnd?: number;
  /** Box 11, Aggregate profit or (loss) on contracts */
  aggregateProfitOnContracts?: number;
  /** Box 13, Bartering */
  bartering?: number;
  /** Boxes 1-3, 5-7, 12, Security details */
  securityDetails?: SecurityDetailIRSForm1099B[];
  /** Second TIN Notice */
  secondTinNotice?: boolean;
}

export const form1099BSchema: Schema<Form1099B> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  accountNumber: ['accountNumber', optional(string())],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  profitOnClosedContracts: ['profitOnClosedContracts', optional(number())],
  unrealizedProfitOpenContractsBegin: [
    'unrealizedProfitOpenContractsBegin',
    optional(number()),
  ],
  unrealizedProfitOpenContractsEnd: [
    'unrealizedProfitOpenContractsEnd',
    optional(number()),
  ],
  aggregateProfitOnContracts: [
    'aggregateProfitOnContracts',
    optional(number()),
  ],
  bartering: ['bartering', optional(number())],
  securityDetails: [
    'securityDetails',
    optional(array(lazy(() => securityDetailIRSForm1099BSchema))),
  ],
  secondTinNotice: ['secondTinNotice', optional(boolean())],
});
