/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CodeAndAmount, codeAndAmountSchema } from './codeAndAmount';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import {
  StateAndLocalTaxWithholding,
  stateAndLocalTaxWithholdingSchema,
} from './stateAndLocalTaxWithholding';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Boxes 1-20 of Previously reported Wage and Tax Statement */
export interface FormW21 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Control number */
  controlNumber?: string;
  /** Box 1, Wages, tips, other compensation */
  wages?: number;
  /** Box 2, Federal income tax withheld */
  federalTaxWithheld?: number;
  /** Box 3, Social security wages */
  socialSecurityWages?: number;
  /** Box 4, Social security tax withheld */
  socialSecurityTaxWithheld?: number;
  /** Box 5, Medicare wages and tips */
  medicareWages?: number;
  /** Box 6, Medicare tax withheld */
  medicareTaxWithheld?: number;
  /** Box 7, Social security tips */
  socialSecurityTips?: number;
  /** Box 8, Allocated tips */
  allocatedTips?: number;
  /** Box 10, Dependent care benefits */
  dependentCareBenefit?: number;
  /** Box 11, Nonqualified plans */
  nonQualifiedPlan?: number;
  /** Box 12, Codes and amounts */
  codes?: CodeAndAmount[];
  /** Box 13, Statutory employee */
  statutory?: boolean;
  /** Box 13, Retirement plan */
  retirementPlan?: boolean;
  /** Box 13, Third-party sick pay */
  thirdPartySickPay?: boolean;
  /** Employee Stock Purchase Plan Qualified Disposition amount */
  esppQualified?: number;
  /** Employee Stock Purchase Plan Nonqualified Disposition amount */
  esppNonQualified?: number;
  /** Box 14, Other descriptions and amounts */
  other?: DescriptionAndAmount[];
  /** Boxes 15-20, State and Local tax withholding */
  stateAndLocal?: StateAndLocalTaxWithholding[];
}

export const formW21Schema: Schema<FormW21> = object({
  taxYear: ['taxYear', optional(number())],
  corrected: ['corrected', optional(boolean())],
  accountId: ['accountId', optional(string())],
  taxFormId: ['taxFormId', optional(string())],
  taxFormDate: ['taxFormDate', optional(string())],
  additionalInformation: ['additionalInformation', optional(string())],
  taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
  issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
  attributes: [
    'attributes',
    optional(array(lazy(() => taxFormAttributeSchema))),
  ],
  error: ['error', optional(lazy(() => error2Schema))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  controlNumber: ['controlNumber', optional(string())],
  wages: ['wages', optional(number())],
  federalTaxWithheld: ['federalTaxWithheld', optional(number())],
  socialSecurityWages: ['socialSecurityWages', optional(number())],
  socialSecurityTaxWithheld: ['socialSecurityTaxWithheld', optional(number())],
  medicareWages: ['medicareWages', optional(number())],
  medicareTaxWithheld: ['medicareTaxWithheld', optional(number())],
  socialSecurityTips: ['socialSecurityTips', optional(number())],
  allocatedTips: ['allocatedTips', optional(number())],
  dependentCareBenefit: ['dependentCareBenefit', optional(number())],
  nonQualifiedPlan: ['nonQualifiedPlan', optional(number())],
  codes: ['codes', optional(array(lazy(() => codeAndAmountSchema)))],
  statutory: ['statutory', optional(boolean())],
  retirementPlan: ['retirementPlan', optional(boolean())],
  thirdPartySickPay: ['thirdPartySickPay', optional(boolean())],
  esppQualified: ['esppQualified', optional(number())],
  esppNonQualified: ['esppNonQualified', optional(number())],
  other: ['other', optional(array(lazy(() => descriptionAndAmountSchema)))],
  stateAndLocal: [
    'stateAndLocal',
    optional(array(lazy(() => stateAndLocalTaxWithholdingSchema))),
  ],
});
