/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FrequencyEnum
 */
export enum FrequencyEnum {
  ANNUALLY = 'ANNUALLY',
  BIWEEKLY = 'BIWEEKLY',
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
  SEMIANNUALLY = 'SEMIANNUALLY',
  SEMIMONTHLY = 'SEMIMONTHLY',
  WEEKLY = 'WEEKLY',
}

/**
 * Schema for FrequencyEnum
 */
export const frequencyEnumSchema: Schema<FrequencyEnum> = stringEnum(
  FrequencyEnum
);
