/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { ActionEnum, actionEnumSchema } from './actionEnum';
import { TypeEnum, typeEnumSchema } from './typeEnum';

/** REST application constraint (Hypermedia As The Engine Of Application State) */
export interface HATEOASLink {
  /** URL to invoke the action on the resource */
  href: string;
  /** HTTP Method to use for the request */
  action?: ActionEnum;
  /** Content-types that can be used in the Accept header. */
  types?: TypeEnum[];
}

export const hATEOASLinkSchema: Schema<HATEOASLink> = object({
  href: ['href', string()],
  action: ['action', optional(actionEnumSchema)],
  types: ['types', optional(array(typeEnumSchema))],
});
