/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { IndividualName1, individualName1Schema } from './individualName1';
import {
  MonthAbbreviationEnum,
  monthAbbreviationEnumSchema,
} from './monthAbbreviationEnum';

/** Used on Form 1095-B Part IV and Form 1095-C Part III */
export interface HealthInsuranceCoveredIndividual {
  /** Name of responsible individual */
  name?: IndividualName1;
  /** Social security number or other TIN */
  tin?: string;
  /** Date of birth */
  dateOfBirth?: string;
  /** Covered all 12 months */
  coveredAll12Months?: boolean;
  /** Months covered */
  coveredMonths?: MonthAbbreviationEnum[];
}

export const healthInsuranceCoveredIndividualSchema: Schema<HealthInsuranceCoveredIndividual> = object(
  {
    name: ['name', optional(lazy(() => individualName1Schema))],
    tin: ['tin', optional(string())],
    dateOfBirth: ['dateOfBirth', optional(string())],
    coveredAll12Months: ['coveredAll12Months', optional(boolean())],
    coveredMonths: [
      'coveredMonths',
      optional(array(monthAbbreviationEnumSchema)),
    ],
  }
);
