/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  CoverageMonth1Enum,
  coverageMonth1EnumSchema,
} from './coverageMonth1Enum';

/** Used on Form 1095-A Part III */
export interface HealthInsuranceCoverage {
  /** Monthly enrollment premiums */
  enrollmentPremium?: number;
  /** Monthly second lowest cost silver plan (SLCSP) premium */
  slcspPremium?: number;
  /** Monthly advance payment of premium tax credit */
  advancePremiumTaxCreditPayment?: number;
  /** Month of coverage */
  month?: CoverageMonth1Enum;
}

export const healthInsuranceCoverageSchema: Schema<HealthInsuranceCoverage> = object(
  {
    enrollmentPremium: ['enrollmentPremium', optional(number())],
    slcspPremium: ['slcspPremium', optional(number())],
    advancePremiumTaxCreditPayment: [
      'advancePremiumTaxCreditPayment',
      optional(number()),
    ],
    month: ['month', optional(coverageMonth1EnumSchema)],
  }
);
