/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HeldInAccountEnum
 */
export enum HeldInAccountEnum {
  CASH = 'CASH',
  MARGIN = 'MARGIN',
  SHORT = 'SHORT',
  OTHER = 'OTHER',
}

/**
 * Schema for HeldInAccountEnum
 */
export const heldInAccountEnumSchema: Schema<HeldInAccountEnum> = stringEnum(
  HeldInAccountEnum
);
