/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  SecurityIdTypeEnum,
  securityIdTypeEnumSchema,
} from './securityIdTypeEnum';
import { TaxLot1, taxLot1Schema } from './taxLot1';

export interface Holding {
  /** Long term persistent identity of the holding */
  holdingId?: string;
  /** Unique identifier of the security. */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdTypeEnum;
  /** Breakdown by tax lot. */
  taxLots?: TaxLot1[];
}

export const holdingSchema: Schema<Holding> = object({
  holdingId: ['holdingId', optional(string())],
  securityId: ['securityId', optional(string())],
  securityIdType: ['securityIdType', optional(securityIdTypeEnumSchema)],
  taxLots: ['taxLots', optional(array(lazy(() => taxLot1Schema)))],
});
