/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { TaxLot2, taxLot2Schema } from './taxLot2';

export interface Holding1 {
  holdingId?: string;
  securityId?: string;
  securityIdType?: string;
  taxLots?: TaxLot2[];
}

export const holding1Schema: Schema<Holding1> = object({
  holdingId: ['holdingId', optional(string())],
  securityId: ['securityId', optional(string())],
  securityIdType: ['securityIdType', optional(string())],
  taxLots: ['taxLots', optional(array(lazy(() => taxLot2Schema)))],
});
