/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HoldingSubTypeEnum
 */
export enum HoldingSubTypeEnum {
  MONEYMARKET = 'MONEYMARKET',
  CASH = 'CASH',
}

/**
 * Schema for HoldingSubTypeEnum
 */
export const holdingSubTypeEnumSchema: Schema<HoldingSubTypeEnum> = stringEnum(
  HoldingSubTypeEnum
);
