/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for HoldingTypeEnum
 */
export enum HoldingTypeEnum {
  STOCK = 'STOCK',
  BOND = 'BOND',
  MUTUALFUND = 'MUTUALFUND',
  CD = 'CD',
  ANNUITY = 'ANNUITY',
  OPTION = 'OPTION',
  OTHER = 'OTHER',
}

/**
 * Schema for HoldingTypeEnum
 */
export const holdingTypeEnumSchema: Schema<HoldingTypeEnum> = stringEnum(
  HoldingTypeEnum
);
