/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncomeTypeEnum
 */
export enum IncomeTypeEnum {
  CGLONG = 'CGLONG',
  CGSHORT = 'CGSHORT',
  MISC = 'MISC',
}

/**
 * Schema for IncomeTypeEnum
 */
export const incomeTypeEnumSchema: Schema<IncomeTypeEnum> = stringEnum(
  IncomeTypeEnum
);
