/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Individual issuer or recipient name */
export interface IndividualName4 {
  /** First name */
  first?: string;
  /** Middle initial */
  middle?: string;
  /** Last name */
  last?: string;
  /** Generational or academic suffix */
  suffix?: string;
}

export const individualName4Schema: Schema<IndividualName4> = object({
  first: ['first', optional(string())],
  middle: ['middle', optional(string())],
  last: ['last', optional(string())],
  suffix: ['suffix', optional(string())],
});
