/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Industry code and type */
export interface IndustryCode {
  type?: string;
  code?: string;
}

export const industryCodeSchema: Schema<IndustryCode> = object({
  type: ['type', optional(string())],
  code: ['code', optional(string())],
});
