/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InterestRateTypeEnum
 */
export enum InterestRateTypeEnum {
  FIXED = 'FIXED',
  VARIABLE = 'VARIABLE',
}

/**
 * Schema for InterestRateTypeEnum
 */
export const interestRateTypeEnumSchema: Schema<InterestRateTypeEnum> = stringEnum(
  InterestRateTypeEnum
);
