/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Inv401kSource1Enum
 */
export enum Inv401kSource1Enum {
  PRETAX = 'PRETAX',
  AFTERTAX = 'AFTERTAX',
  MATCH = 'MATCH',
  PROFITSHARING = 'PROFITSHARING',
  ROLLOVER = 'ROLLOVER',
  OTHERVEST = 'OTHERVEST',
  OTHERNONVEST = 'OTHERNONVEST',
}

/**
 * Schema for Inv401kSource1Enum
 */
export const inv401kSource1EnumSchema: Schema<Inv401kSource1Enum> = stringEnum(
  Inv401kSource1Enum
);
