/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Inv401kSourceEnum
 */
export enum Inv401kSourceEnum {
  AFTERTAX = 'AFTERTAX',
  MATCH = 'MATCH',
  OTHERNONVEST = 'OTHERNONVEST',
  OTHERVEST = 'OTHERVEST',
  PRETAX = 'PRETAX',
  PROFITSHARING = 'PROFITSHARING',
  ROLLOVER = 'ROLLOVER',
}

/**
 * Schema for Inv401kSourceEnum
 */
export const inv401kSourceEnumSchema: Schema<Inv401kSourceEnum> = stringEnum(
  Inv401kSourceEnum
);
