/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Inv401kSurceEnum
 */
export enum Inv401kSurceEnum {
  PRETAX = 'PRETAX',
  AFTERTAX = 'AFTERTAX',
  MATCH = 'MATCH',
  PROFITSHARING = 'PROFITSHARING',
  ROLLOVER = 'ROLLOVER',
  OTHERVEST = 'OTHERVEST',
  OTHERNONVEST = 'OTHERNONVEST',
}

/**
 * Schema for Inv401kSurceEnum
 */
export const inv401kSurceEnumSchema: Schema<Inv401kSurceEnum> = stringEnum(
  Inv401kSurceEnum
);
