/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvestmentSaleTypeEnum
 */
export enum InvestmentSaleTypeEnum {
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
  EMPLOYEESTOCKPURCHASEPLAN = 'EMPLOYEE_STOCK_PURCHASE_PLAN',
  INCENTIVESTOCKOPTION = 'INCENTIVE_STOCK_OPTION',
  NONQUALIFIEDSTOCKOPTIONS = 'NONQUALIFIED_STOCK_OPTIONS',
  OTHER = 'OTHER',
  RESTRICTEDSTOCK = 'RESTRICTED_STOCK',
  RESTRICTEDSTOCKUNITS = 'RESTRICTED_STOCK_UNITS',
}

/**
 * Schema for InvestmentSaleTypeEnum
 */
export const investmentSaleTypeEnumSchema: Schema<InvestmentSaleTypeEnum> = stringEnum(
  InvestmentSaleTypeEnum
);
