/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  InvestmentsAccounts,
  investmentsAccountsSchema,
} from './containers/investmentsAccounts';

export interface Investments {
  /** An array of accounts with entity types dependent on the account type (deposit, investment, loan, line of credit, annuity or insurance) */
  accounts?: InvestmentsAccounts[];
}

export const investmentsSchema: Schema<Investments> = object({
  accounts: ['accounts', optional(array(investmentsAccountsSchema))],
});
