/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { BalanceType1Enum, balanceType1EnumSchema } from './balanceType1Enum';
import { CurrencyEntity, currencyEntitySchema } from './currencyEntity';

export interface InvestmentBalanceList {
  /** Name of the balance. */
  balanceName?: string;
  /** Description of balance. */
  balanceDescription?: string;
  /** The type of an investment balance. AMOUNT or PERCENTAGE. */
  balanceType?: BalanceType1Enum;
  /** Value of balance name. */
  balanceValue?: number;
  /** Date as of this balance. */
  balanceDate?: string;
  /** Indicates the currency code used by the account. May also include currency rate. */
  currency?: CurrencyEntity;
}

export const investmentBalanceListSchema: Schema<InvestmentBalanceList> = object(
  {
    balanceName: ['balanceName', optional(string())],
    balanceDescription: ['balanceDescription', optional(string())],
    balanceType: ['balanceType', optional(balanceType1EnumSchema)],
    balanceValue: ['balanceValue', optional(number())],
    balanceDate: ['balanceDate', optional(string())],
    currency: ['currency', optional(lazy(() => currencyEntitySchema))],
  }
);
