/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';

export interface LineItem {
  /** The amount of money attributable to this line item */
  amount?: number;
  /** Check number */
  checkNumber?: number;
  /** The description of the line item */
  description?: string;
  /** Array of image identifiers (unique to transaction) used to retrieve images of check or transaction receipt */
  imageIds?: string[];
  /** Links (unique to this Transaction) used to retrieve images of checks or transaction receipts, or invoke other APIs */
  links?: HATEOASLink[];
  /** Secondary item description */
  memo?: string;
  /** A reference number */
  reference?: string;
}

export const lineItemSchema: Schema<LineItem> = object({
  amount: ['amount', optional(number())],
  checkNumber: ['checkNumber', optional(number())],
  description: ['description', optional(string())],
  imageIds: ['imageIds', optional(array(string()))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  memo: ['memo', optional(string())],
  reference: ['reference', optional(string())],
});
