/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Next, nextSchema } from './next';
import { Prev, prevSchema } from './prev';

export interface Links {
  next?: Next;
  prev?: Prev;
}

export const linksSchema: Schema<Links> = object({
  next: ['next', optional(lazy(() => nextSchema))],
  prev: ['prev', optional(lazy(() => prevSchema))],
});
