/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { BalanceTypeEnum, balanceTypeEnumSchema } from './balanceTypeEnum';
import {
  CompoundingPeriodEnum,
  compoundingPeriodEnumSchema,
} from './compoundingPeriodEnum';
import { CurrencyEntity, currencyEntitySchema } from './currencyEntity';
import {
  FiAttributeEntity,
  fiAttributeEntitySchema,
} from './fiAttributeEntity';
import {
  InterestRateTypeEnum,
  interestRateTypeEnumSchema,
} from './interestRateTypeEnum';
import {
  PaymentFrequencyEnum,
  paymentFrequencyEnumSchema,
} from './paymentFrequencyEnum';
import { StatusEnum, statusEnumSchema } from './statusEnum';

/** Loan Account */
export interface LoanAccount {
  /** Long-term persistent identity of the account. Not an account number. This identity must be unique to the owning institution. */
  accountId?: string;
  /** The type of an account. For instance, CHECKING, SAVINGS, 401K, etc. */
  accountType?: string;
  /** Account display number for the end user’s handle at owning institution. This is to be displayed by the Interface Provider. */
  accountNumberDisplay?: string;
  /** Indicates the currency code used by the account. May also include currency rate. */
  currency?: CurrencyEntity;
  description?: string;
  fiAttributes?: FiAttributeEntity[];
  /** Name given by the user. Used in UIs to assist in account selection */
  nickname?: string;
  /** Marketed product name for this account.  Used in UIs to assist in account selection */
  productName?: string;
  /** The status of an account. */
  status?: StatusEnum;
  /** The line of business, such as consumer, consumer joint, small business, corporate, etc. */
  lineOfBusiness?: string;
  /** ASSET (positive transaction amount increases balance), LIABILITY (positive transaction amount decreases balance) */
  balanceType?: BalanceTypeEnum;
  /** Interest Rate of Account */
  interestRate?: number;
  /** The type of interest rate. FIXED or VARIABLE. */
  interestRateType?: InterestRateTypeEnum;
  /** Date of account’s interest rate */
  interestRateAsOf?: string;
  /** Date that last transaction occurred on account */
  lastActivityDate?: string;
  /** MICR Number */
  micrNumber?: string;
  /** Long-term persistent identity of the parent account. This is used to group accounts. */
  parentAccountId?: string;
  /** Previous Interest Rate of Account */
  priorInterestRate?: number;
  /** Account is eligible for incoming transfers */
  transferIn?: boolean;
  /** Account is eligible for outgoing transfers */
  transferOut?: boolean;
  compoundingPeriod?: CompoundingPeriodEnum;
  /** Term of loan in months */
  loanTerm?: number;
  /** Maturity date */
  maturityDate?: string;
  /** Loan origination date */
  originatingDate?: string;
  paymentFrequency?: PaymentFrequencyEnum;
  /** Total number of payments */
  totalNumberOfPayments?: number;
}

export const loanAccountSchema: Schema<LoanAccount> = object({
  accountId: ['accountId', optional(string())],
  accountType: ['accountType', optional(string())],
  accountNumberDisplay: ['accountNumberDisplay', optional(string())],
  currency: ['currency', optional(lazy(() => currencyEntitySchema))],
  description: ['description', optional(string())],
  fiAttributes: [
    'fiAttributes',
    optional(array(lazy(() => fiAttributeEntitySchema))),
  ],
  nickname: ['nickname', optional(string())],
  productName: ['productName', optional(string())],
  status: ['status', optional(statusEnumSchema)],
  lineOfBusiness: ['lineOfBusiness', optional(string())],
  balanceType: ['balanceType', optional(balanceTypeEnumSchema)],
  interestRate: ['interestRate', optional(number())],
  interestRateType: ['interestRateType', optional(interestRateTypeEnumSchema)],
  interestRateAsOf: ['interestRateAsOf', optional(string())],
  lastActivityDate: ['lastActivityDate', optional(string())],
  micrNumber: ['micrNumber', optional(string())],
  parentAccountId: ['parentAccountId', optional(string())],
  priorInterestRate: ['priorInterestRate', optional(number())],
  transferIn: ['transferIn', optional(boolean())],
  transferOut: ['transferOut', optional(boolean())],
  compoundingPeriod: [
    'compoundingPeriod',
    optional(compoundingPeriodEnumSchema),
  ],
  loanTerm: ['loanTerm', optional(number())],
  maturityDate: ['maturityDate', optional(string())],
  originatingDate: ['originatingDate', optional(string())],
  paymentFrequency: ['paymentFrequency', optional(paymentFrequencyEnumSchema)],
  totalNumberOfPayments: ['totalNumberOfPayments', optional(number())],
});
