/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  DebitCreditMemoEnum,
  debitCreditMemoEnumSchema,
} from './debitCreditMemoEnum';
import {
  FiAttributeEntity,
  fiAttributeEntitySchema,
} from './fiAttributeEntity';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { LineItem, lineItemSchema } from './lineItem';
import { PaymentDetails, paymentDetailsSchema } from './paymentDetails';
import { Status1Enum, status1EnumSchema } from './status1Enum';
import {
  TransactionType3Enum,
  transactionType3EnumSchema,
} from './transactionType3Enum';

/** Loan Transaction */
export interface LoanTransaction {
  /** Corresponds to AccountId in Account */
  accountId?: string;
  /**
   * The amount of money in the account currency.
   * If balanceType is `ASSET`:
   *   1. If `debitCreditMemo` = `DEBIT`, sign is "+" or not present
   *   2. If `CREDIT`, sign is "-"
   * If balanceType is `LIABILITY`:
   *   1. If `debitCreditMemo` = `DEBIT`, sign is "-"
   *   2. If `CREDIT`, sign is "+" or not present
   */
  amount?: number;
  /** Transaction category, preferably MCC or SIC. */
  category?: string;
  /** Akoya will ensure that this is correctly populated with one of DEBIT or CREDIT and matches the sign of the status field. */
  debitCreditMemo?: DebitCreditMemoEnum;
  /** The description of the transaction */
  description?: string;
  /** Array of image identifiers (unique to transaction) used to retrieve images of check or transaction receipt. */
  imageIds?: string[];
  /** Array of FI-specific attributes */
  fiAttributes?: FiAttributeEntity[];
  /** The amount of money in the foreign currency */
  foreignAmount?: number;
  /** The ISO 4217 code of the foreign currency */
  foreignCurrency?: string;
  /** Breakdown of the transaction details */
  lineItem?: LineItem[];
  /** Links (unique to this Transaction) used to retrieve images of checks or transaction receipts, or invoke other APIs */
  links?: HATEOASLink[];
  /** Secondary transaction description */
  memo?: string;
  /** The date and time that the transaction was posted to the account. If not provided then TransactionTimestamp can be used as PostedTimeStamp. */
  postedTimestamp?: string;
  /** A tracking reference identifier */
  reference?: string;
  /**
   * Akoya ensures that this field is populated for all transactions which are reversals, otherwise it is null. Either way it is always present.
   * For reverse postings, the identity of the transaction being reversed. For the correction transaction, the identity of the reversing post. For credit card posting transactions, the identity of the authorization transaction.
   */
  referenceTransactionId?: string;
  /** AUTHORIZATION, MEMO, PENDING, or POSTED */
  status?: Status1Enum;
  /** Transaction category detail */
  subCategory?: string;
  /**
   * Long term persistent identity of the transaction (unique to account).
   * Transaction IDs should:
   *   1. be the same for pending and posted
   *   2. be different for reversed transactions
   *   3. `referenceTransactionId` should be present for reversed transactions'
   */
  transactionId?: string;
  /**
   * The date and time that the transaction was added to the server backend systems.
   * Akoya ensures that this field is populated for all transactions to which it applies, otherwise it is null. Either way it is always present.
   */
  transactionTimestamp?: string;
  /** Payment details for some transactions */
  paymentDetails?: PaymentDetails;
  /** LoanTransaction Type */
  transactionType?: TransactionType3Enum;
}

export const loanTransactionSchema: Schema<LoanTransaction> = object({
  accountId: ['accountId', optional(string())],
  amount: ['amount', optional(number())],
  category: ['category', optional(string())],
  debitCreditMemo: ['debitCreditMemo', optional(debitCreditMemoEnumSchema)],
  description: ['description', optional(string())],
  imageIds: ['imageIds', optional(array(string()))],
  fiAttributes: [
    'fiAttributes',
    optional(array(lazy(() => fiAttributeEntitySchema))),
  ],
  foreignAmount: ['foreignAmount', optional(number())],
  foreignCurrency: ['foreignCurrency', optional(string())],
  lineItem: ['lineItem', optional(array(lazy(() => lineItemSchema)))],
  links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
  memo: ['memo', optional(string())],
  postedTimestamp: ['postedTimestamp', optional(string())],
  reference: ['reference', optional(string())],
  referenceTransactionId: ['referenceTransactionId', optional(string())],
  status: ['status', optional(status1EnumSchema)],
  subCategory: ['subCategory', optional(string())],
  transactionId: ['transactionId', optional(string())],
  transactionTimestamp: ['transactionTimestamp', optional(string())],
  paymentDetails: [
    'paymentDetails',
    optional(lazy(() => paymentDetailsSchema)),
  ],
  transactionType: ['transactionType', optional(transactionType3EnumSchema)],
});
