/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for LoanPaymentFrequencyEnum
 */
export enum LoanPaymentFrequencyEnum {
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  TWICEMONTHLY = 'TWICEMONTHLY',
  MONTHLY = 'MONTHLY',
  FOURWEEKS = 'FOURWEEKS',
  BIMONTHLY = 'BIMONTHLY',
  QUARTERLY = 'QUARTERLY',
  SEMIANNUALLY = 'SEMIANNUALLY',
  ANNUALLY = 'ANNUALLY',
  OTHER = 'OTHER',
}

/**
 * Schema for LoanPaymentFrequencyEnum
 */
export const loanPaymentFrequencyEnumSchema: Schema<LoanPaymentFrequencyEnum> = stringEnum(
  LoanPaymentFrequencyEnum
);
