/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Amount of local income tax withheld, if any */
export interface LocalTaxWithholding1 {
  /** Amount of local income tax withheld */
  taxWithheld?: number;
  /** Locality name */
  localityName?: string;
  /** Income amount for local tax purposes */
  income?: number;
}

export const localTaxWithholding1Schema: Schema<LocalTaxWithholding1> = object({
  taxWithheld: ['taxWithheld', optional(number())],
  localityName: ['localityName', optional(string())],
  income: ['income', optional(number())],
});
