/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Income in a locality and its tax withholding */
export interface LocalTaxWithholding {
  /** Amount of local income tax withheld */
  taxWithheld?: number;
  /** Locality name */
  localityName?: string;
  /** Income amount for local tax purposes */
  income?: number;
}

export const localTaxWithholdingSchema: Schema<LocalTaxWithholding> = object({
  taxWithheld: ['taxWithheld', optional(number())],
  localityName: ['localityName', optional(string())],
  income: ['income', optional(number())],
});
