/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ModeEnum
 */
export enum ModeEnum {
  Raw = 'raw',
  Standard = 'standard',
}

/**
 * Schema for ModeEnum
 */
export const modeEnumSchema: Schema<ModeEnum> = stringEnum(ModeEnum);
