/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MonthAbbreviationEnum
 */
export enum MonthAbbreviationEnum {
  JAN = 'JAN',
  FEB = 'FEB',
  MAR = 'MAR',
  APR = 'APR',
  MAY = 'MAY',
  JUN = 'JUN',
  JUL = 'JUL',
  AUG = 'AUG',
  SEP = 'SEP',
  OCT = 'OCT',
  NOV = 'NOV',
  DEC = 'DEC',
}

/**
 * Schema for MonthAbbreviationEnum
 */
export const monthAbbreviationEnumSchema: Schema<MonthAbbreviationEnum> = stringEnum(
  MonthAbbreviationEnum
);
