/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import {
  MonthAbbreviation1Enum,
  monthAbbreviation1EnumSchema,
} from './monthAbbreviation1Enum';

/** Month and amount pair used on IRS Form 1099-K, etc. */
export interface MonthAndAmount {
  /** Month */
  month?: MonthAbbreviation1Enum;
  /** Amount */
  amount?: number;
}

export const monthAndAmountSchema: Schema<MonthAndAmount> = object({
  month: ['month', optional(monthAbbreviation1EnumSchema)],
  amount: ['amount', optional(number())],
});
