/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MutualFundTypeEnum
 */
export enum MutualFundTypeEnum {
  OPENEND = 'OPENEND',
  CLOSEEND = 'CLOSEEND',
  OTHER = 'OTHER',
}

/**
 * Schema for MutualFundTypeEnum
 */
export const mutualFundTypeEnumSchema: Schema<MutualFundTypeEnum> = stringEnum(
  MutualFundTypeEnum
);
