/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';
import {
  MutualFundTypeEnum,
  mutualFundTypeEnumSchema,
} from './mutualFundTypeEnum';

/** Information about the mutual fund security specific to the type of security */
export interface MutualFundSecurityEntity {
  /** Mutual fund type */
  mutualFundType?: MutualFundTypeEnum;
  /** Units in the FI's street name, positive quantity */
  unitsStreet?: number;
  /** Units in user's name directly, positive  quantity */
  unitsUser?: number;
  /** Reinvest dividends */
  reinvestDividends?: boolean;
  /** Reinvest capital gains */
  reinvestCapitalGains?: boolean;
  /** Current yield reported as portion of the fund's assets */
  yield?: number;
  /** As-of date for yield value */
  yieldAsOfDate?: string;
}

export const mutualFundSecurityEntitySchema: Schema<MutualFundSecurityEntity> = object(
  {
    mutualFundType: ['mutualFundType', optional(mutualFundTypeEnumSchema)],
    unitsStreet: ['unitsStreet', optional(number())],
    unitsUser: ['unitsUser', optional(number())],
    reinvestDividends: ['reinvestDividends', optional(boolean())],
    reinvestCapitalGains: ['reinvestCapitalGains', optional(boolean())],
    yield: ['yield', optional(number())],
    yieldAsOfDate: ['yieldAsOfDate', optional(string())],
  }
);
