/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The end-user's name */
export interface Name {
  /** First or given name. This data element may contain first & last name if not separated. */
  first?: string;
  middle?: string;
  last?: string;
  /** Name prefix, e.g. Mr. */
  prefix?: string;
  /** Generational or academic suffix */
  suffix?: string;
  /** Company name */
  company?: string;
}

export const nameSchema: Schema<Name> = object({
  first: ['first', optional(string())],
  middle: ['middle', optional(string())],
  last: ['last', optional(string())],
  prefix: ['prefix', optional(string())],
  suffix: ['suffix', optional(string())],
  company: ['company', optional(string())],
});
