/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Next {
  href?: string;
}

export const nextSchema: Schema<Next> = object({
  href: ['href', optional(string())],
});
