/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  Inv401kSourceEnum,
  inv401kSourceEnumSchema,
} from './inv401kSourceEnum';
import {
  OrderDurationEnum,
  orderDurationEnumSchema,
} from './orderDurationEnum';
import { OrderTypeEnum, orderTypeEnumSchema } from './orderTypeEnum';
import {
  SecurityIdTypeEnum,
  securityIdTypeEnumSchema,
} from './securityIdTypeEnum';
import { SubAccountEnum, subAccountEnumSchema } from './subAccountEnum';
import { UnitTypeEnum, unitTypeEnumSchema } from './unitTypeEnum';

/** Information on an open order. */
export interface OpenOrderEntity {
  /** Long term persistent identity of the order. Id for this order transaction. */
  orderId?: string;
  /** Unique identifier of the security. */
  securityId?: string;
  /** Security identifier type */
  securityIdType?: SecurityIdTypeEnum;
  /** Market symbol */
  symbol?: string;
  /** Description of order */
  description?: string;
  /** Number of units (shares, bonds, etc.) */
  units?: number;
  /** Type of order. */
  orderType?: OrderTypeEnum;
  /** Order date */
  orderDate?: string;
  /** Unit price */
  unitPrice?: number;
  /** Type of unit. */
  unitType?: UnitTypeEnum;
  /** This order is good for DAY, GOODTILLCANCEL, IMMEDIATE */
  orderDuration?: OrderDurationEnum;
  subAccount?: SubAccountEnum;
  /** Limit Price */
  limitPrice?: number;
  /** Stop price */
  stopPrice?: number;
  /** For 401(k) accounts, source of money for this order. Default if not present is OTHERNONVEST. */
  inv401kSource?: Inv401kSourceEnum;
}

export const openOrderEntitySchema: Schema<OpenOrderEntity> = object({
  orderId: ['orderId', optional(string())],
  securityId: ['securityId', optional(string())],
  securityIdType: ['securityIdType', optional(securityIdTypeEnumSchema)],
  symbol: ['symbol', optional(string())],
  description: ['description', optional(string())],
  units: ['units', optional(number())],
  orderType: ['orderType', optional(orderTypeEnumSchema)],
  orderDate: ['orderDate', optional(string())],
  unitPrice: ['unitPrice', optional(number())],
  unitType: ['unitType', optional(unitTypeEnumSchema)],
  orderDuration: ['orderDuration', optional(orderDurationEnumSchema)],
  subAccount: ['subAccount', optional(subAccountEnumSchema)],
  limitPrice: ['limitPrice', optional(number())],
  stopPrice: ['stopPrice', optional(number())],
  inv401kSource: ['inv401kSource', optional(inv401kSourceEnumSchema)],
});
