/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OptionTypeEnum
 */
export enum OptionTypeEnum {
  CALL = 'CALL',
  PUT = 'PUT',
}

/**
 * Schema for OptionTypeEnum
 */
export const optionTypeEnumSchema: Schema<OptionTypeEnum> = stringEnum(
  OptionTypeEnum
);
