/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { OptionTypeEnum, optionTypeEnumSchema } from './optionTypeEnum';
import { SecuredEnum, securedEnumSchema } from './securedEnum';

/** Information about the option security specific to the type of security */
export interface OptionSecurityEntity {
  /** How the option is secured */
  secured?: SecuredEnum;
  optionType?: OptionTypeEnum;
  /** Strike price / Unit price */
  strikePrice?: number;
  /** Expiration date of option */
  expireDate?: string;
  /** Shares per contract */
  sharesPerContract?: number;
}

export const optionSecurityEntitySchema: Schema<OptionSecurityEntity> = object({
  secured: ['secured', optional(securedEnumSchema)],
  optionType: ['optionType', optional(optionTypeEnumSchema)],
  strikePrice: ['strikePrice', optional(number())],
  expireDate: ['expireDate', optional(string())],
  sharesPerContract: ['sharesPerContract', optional(number())],
});
