/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderTypeEnum
 */
export enum OrderTypeEnum {
  BUY = 'BUY',
  SELL = 'SELL',
  BUYTOCOVER = 'BUYTOCOVER',
  BUYTOOPEN = 'BUYTOOPEN',
  SELLTOCOVER = 'SELLTOCOVER',
  SELLTOOPEN = 'SELLTOOPEN',
  SELLSHORT = 'SELLSHORT',
  SELLCLOSE = 'SELLCLOSE',
}

/**
 * Schema for OrderTypeEnum
 */
export const orderTypeEnumSchema: Schema<OrderTypeEnum> = stringEnum(
  OrderTypeEnum
);
