/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderDurationEnum
 */
export enum OrderDurationEnum {
  DAY = 'DAY',
  GOODTILLCANCEL = 'GOODTILLCANCEL',
  IMMEDIATE = 'IMMEDIATE',
}

/**
 * Schema for OrderDurationEnum
 */
export const orderDurationEnumSchema: Schema<OrderDurationEnum> = stringEnum(
  OrderDurationEnum
);
