/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Information about the security specific to the type of security */
export interface OtherSecurityEntity {
  /** Description of Other Security */
  typeDescription?: string;
}

export const otherSecurityEntitySchema: Schema<OtherSecurityEntity> = object({
  typeDescription: ['typeDescription', optional(string())],
});
