/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';

export interface PaginatedArray {
  links?: Links;
}

export const paginatedArraySchema: Schema<PaginatedArray> = object({
  links: ['links', optional(lazy(() => linksSchema))],
});
