/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentFrequency1Enum
 */
export enum PaymentFrequency1Enum {
  ANNUALLY = 'ANNUALLY',
  QUARTERLY = 'QUARTERLY',
  MONTHLY = 'MONTHLY',
  WEEKLY = 'WEEKLY',
}

/**
 * Schema for PaymentFrequency1Enum
 */
export const paymentFrequency1EnumSchema: Schema<PaymentFrequency1Enum> = stringEnum(
  PaymentFrequency1Enum
);
