/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentFrequencyEnum
 */
export enum PaymentFrequencyEnum {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  SEMIMONTHLY = 'SEMIMONTHLY',
  MONTHLY = 'MONTHLY',
  SEMIANNUALLY = 'SEMIANNUALLY',
  ANNUALLY = 'ANNUALLY',
}

/**
 * Schema for PaymentFrequencyEnum
 */
export const paymentFrequencyEnumSchema: Schema<PaymentFrequencyEnum> = stringEnum(
  PaymentFrequencyEnum
);
