/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

/** Payment details for some transactions */
export interface PaymentDetails {
  /** The amount of payment applied to escrow */
  escrowAmount?: number;
  /** The amount of payment applied to fees */
  feesAmount?: number;
  /** The amount of payment applied to life/health/accident insurance on the loan */
  insuranceAmount?: number;
  /** The amount of payment applied to interest */
  interestAmount?: number;
  /** The amount of payment applied to PMI */
  pmiAmount?: number;
  /** The amount of payment applied to principal */
  principalAmount?: number;
}

export const paymentDetailsSchema: Schema<PaymentDetails> = object({
  escrowAmount: ['escrowAmount', optional(number())],
  feesAmount: ['feesAmount', optional(number())],
  insuranceAmount: ['insuranceAmount', optional(number())],
  interestAmount: ['interestAmount', optional(number())],
  pmiAmount: ['pmiAmount', optional(number())],
  principalAmount: ['principalAmount', optional(number())],
});
