/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { FrequencyEnum, frequencyEnumSchema } from './frequencyEnum';

/** Information about a pension source. */
export interface PensionSourceEntity {
  /** Name of the Source */
  displayName?: string;
  /** Benefit Amount */
  amount?: number;
  /** Form of payment */
  paymentOption?: string;
  /** Date benefit was calculated */
  asOfDate?: string;
  frequency?: FrequencyEnum;
  /** Assumed retirement date ‐ As of date amount is payable */
  startDate?: string;
}

export const pensionSourceEntitySchema: Schema<PensionSourceEntity> = object({
  displayName: ['displayName', optional(string())],
  amount: ['amount', optional(number())],
  paymentOption: ['paymentOption', optional(string())],
  asOfDate: ['asOfDate', optional(string())],
  frequency: ['frequency', optional(frequencyEnumSchema)],
  startDate: ['startDate', optional(string())],
});
