/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PeriodCertainGuaranteeEnum
 */
export enum PeriodCertainGuaranteeEnum {
  EnumNOPERIODCERTAIN = 'NO PERIOD CERTAIN',
  Enum5YEAR = '5-YEAR',
  Enum10YEAR = '10-YEAR',
  Enum20YEAR = '20-YEAR',
  Enum30YEAR = '30-YEAR',
}

/**
 * Schema for PeriodCertainGuaranteeEnum
 */
export const periodCertainGuaranteeEnumSchema: Schema<PeriodCertainGuaranteeEnum> = stringEnum(
  PeriodCertainGuaranteeEnum
);
