/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PolicyPremiumTermEnum
 */
export enum PolicyPremiumTermEnum {
  MONTHLY = 'MONTHLY',
  ANNUAL = 'ANNUAL',
}

/**
 * Schema for PolicyPremiumTermEnum
 */
export const policyPremiumTermEnumSchema: Schema<PolicyPremiumTermEnum> = stringEnum(
  PolicyPremiumTermEnum
);
