/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PositionTypeEnum
 */
export enum PositionTypeEnum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for PositionTypeEnum
 */
export const positionTypeEnumSchema: Schema<PositionTypeEnum> = stringEnum(
  PositionTypeEnum
);
