/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PositionType2Enum
 */
export enum PositionType2Enum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for PositionType2Enum
 */
export const positionType2EnumSchema: Schema<PositionType2Enum> = stringEnum(
  PositionType2Enum
);
