/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PostionTypeEnum
 */
export enum PostionTypeEnum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for PostionTypeEnum
 */
export const postionTypeEnumSchema: Schema<PostionTypeEnum> = stringEnum(
  PostionTypeEnum
);
