/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResultTypeEnum
 */
export enum ResultTypeEnum {
  Details = 'details',
  Lightweight = 'lightweight',
}

/**
 * Schema for ResultTypeEnum
 */
export const resultTypeEnumSchema: Schema<ResultTypeEnum> = stringEnum(
  ResultTypeEnum
);
