/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Address3, address3Schema } from './address3';
import { DateAndAmount, dateAndAmountSchema } from './dateAndAmount';
import {
  DescriptionAndAmount,
  descriptionAndAmountSchema,
} from './descriptionAndAmount';
import { Error2, error2Schema } from './error2';
import { HATEOASLink, hATEOASLinkSchema } from './hATEOASLink';
import { TaxFormAttribute, taxFormAttributeSchema } from './taxFormAttribute';
import { TaxParty1, taxParty1Schema } from './taxParty1';
import { TaxParty8, taxParty8Schema } from './taxParty8';
import {
  TypeFormType2Enum,
  typeFormType2EnumSchema,
} from './typeFormType2Enum';

/** Royalty Income Statement for IRS Form 1040 Schedule E */
export interface RoyaltyIncomeStatement {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** True to indicate this is a corrected tax form */
  corrected?: boolean;
  /** Long-term persistent identity of the source account. Not the account number */
  accountId?: string;
  /** Long-term persistent id for this tax form. Depending upon the data provider, this may be the same id as the enclosing tax statement id, or this may be a different id, or this id may be omitted. */
  taxFormId?: string;
  /** Date of production or delivery of the tax form */
  taxFormDate?: string;
  /** Additional explanation text or content about this tax form */
  additionalInformation?: string;
  /** Enumerated name of the tax form entity e.g. "TaxW2" */
  taxFormType?: TypeFormType2Enum;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  issuer?: TaxParty8;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmitted on enclosing TaxStatement, if it is the same on all its included tax forms. */
  recipient?: TaxParty1;
  /** Additional attributes for this tax form when defined fields are not available. Some specific additional attributes already defined by providers: Fields required by [IRS FIRE](https://www.irs.gov/e-file-providers/filing-information-returns-electronically-fire): Name Control, Type of Identification Number (EIN, SSN, ITIN, ATIN). (ATIN is tax ID number for pending adoptions.) Tax form provider field for taxpayer notification: Recipient Email Address. */
  attributes?: TaxFormAttribute[];
  /** Present if an error was encountered while retrieving this form */
  error?: Error2;
  /** Links to retrieve this form as data or image, or to invoke other APIs */
  links?: HATEOASLink[];
  /** Box 1a, Physical address of property (street, city, state, ZIP code) */
  propertyAddress?: Address3;
  /** Box 3, Royalties received */
  royalties?: number;
  /** Box 5, Advertising */
  advertising?: number;
  /** Box 6, Auto and travel */
  auto?: number;
  /** Box 7, Cleaning and maintenance */
  cleaning?: number;
  /** Box 8, Commissions */
  commissions?: number;
  /** Box 9, Insurance */
  insurance?: number;
  /** Box 10, Legal and other professional fees */
  legal?: number;
  /** Box 11, Management fees */
  managementFees?: number;
  /** Box 12, Mortgage interest paid to banks, etc. */
  mortgageInterest?: number;
  /** Box 13, Other interest */
  otherInterest?: number;
  /** Box 14, Repairs */
  repairs?: number;
  /** Box 15, Supplies */
  supplies?: number;
  /** Box 16, Taxes */
  taxes?: number;
  /** Box 17, Utilities */
  utilities?: number;
  /** Box 18, Depletion */
  depletionExpense?: number;
  /** Box 19, Other expenses */
  otherExpenses?: DescriptionAndAmount[];
  /** Capital expenditures, for use in calculating Depreciation */
  capitalExpenditures?: DateAndAmount[];
}

export const royaltyIncomeStatementSchema: Schema<RoyaltyIncomeStatement> = object(
  {
    taxYear: ['taxYear', optional(number())],
    corrected: ['corrected', optional(boolean())],
    accountId: ['accountId', optional(string())],
    taxFormId: ['taxFormId', optional(string())],
    taxFormDate: ['taxFormDate', optional(string())],
    additionalInformation: ['additionalInformation', optional(string())],
    taxFormType: ['taxFormType', optional(typeFormType2EnumSchema)],
    issuer: ['issuer', optional(lazy(() => taxParty8Schema))],
    recipient: ['recipient', optional(lazy(() => taxParty1Schema))],
    attributes: [
      'attributes',
      optional(array(lazy(() => taxFormAttributeSchema))),
    ],
    error: ['error', optional(lazy(() => error2Schema))],
    links: ['links', optional(array(lazy(() => hATEOASLinkSchema)))],
    propertyAddress: ['propertyAddress', optional(lazy(() => address3Schema))],
    royalties: ['royalties', optional(number())],
    advertising: ['advertising', optional(number())],
    auto: ['auto', optional(number())],
    cleaning: ['cleaning', optional(number())],
    commissions: ['commissions', optional(number())],
    insurance: ['insurance', optional(number())],
    legal: ['legal', optional(number())],
    managementFees: ['managementFees', optional(number())],
    mortgageInterest: ['mortgageInterest', optional(number())],
    otherInterest: ['otherInterest', optional(number())],
    repairs: ['repairs', optional(number())],
    supplies: ['supplies', optional(number())],
    taxes: ['taxes', optional(number())],
    utilities: ['utilities', optional(number())],
    depletionExpense: ['depletionExpense', optional(number())],
    otherExpenses: [
      'otherExpenses',
      optional(array(lazy(() => descriptionAndAmountSchema))),
    ],
    capitalExpenditures: [
      'capitalExpenditures',
      optional(array(lazy(() => dateAndAmountSchema))),
    ],
  }
);
