/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleTermTypeEnum
 */
export enum SaleTermTypeEnum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for SaleTermTypeEnum
 */
export const saleTermTypeEnumSchema: Schema<SaleTermTypeEnum> = stringEnum(
  SaleTermTypeEnum
);
