/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleTermType2Enum
 */
export enum SaleTermType2Enum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for SaleTermType2Enum
 */
export const saleTermType2EnumSchema: Schema<SaleTermType2Enum> = stringEnum(
  SaleTermType2Enum
);
