/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleProceedsTypeEnum
 */
export enum SaleProceedsTypeEnum {
  GROSS = 'GROSS',
  NET = 'NET',
}

/**
 * Schema for SaleProceedsTypeEnum
 */
export const saleProceedsTypeEnumSchema: Schema<SaleProceedsTypeEnum> = stringEnum(
  SaleProceedsTypeEnum
);
