/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleTermType3Enum
 */
export enum SaleTermType3Enum {
  LONG = 'LONG',
  SHORT = 'SHORT',
}

/**
 * Schema for SaleTermType3Enum
 */
export const saleTermType3EnumSchema: Schema<SaleTermType3Enum> = stringEnum(
  SaleTermType3Enum
);
