/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaleProceedsType1Enum
 */
export enum SaleProceedsType1Enum {
  GROSS = 'GROSS',
  NET = 'NET',
}

/**
 * Schema for SaleProceedsType1Enum
 */
export const saleProceedsType1EnumSchema: Schema<SaleProceedsType1Enum> = stringEnum(
  SaleProceedsType1Enum
);
