/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecurityTypeEnum
 */
export enum SecurityTypeEnum {
  STOCK = 'STOCK',
  MUTUALFUND = 'MUTUALFUND',
  DEBT = 'DEBT',
  OPTION = 'OPTION',
  SWEEP = 'SWEEP',
  OTHER = 'OTHER',
  BOND = 'BOND',
}

/**
 * Schema for SecurityTypeEnum
 */
export const securityTypeEnumSchema: Schema<SecurityTypeEnum> = stringEnum(
  SecurityTypeEnum
);
