/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecurityIdTypeEnum
 */
export enum SecurityIdTypeEnum {
  CUSIP = 'CUSIP',
  ISIN = 'ISIN',
  SEDOL = 'SEDOL',
  SICC = 'SICC',
  VALOR = 'VALOR',
  WKN = 'WKN',
}

/**
 * Schema for SecurityIdTypeEnum
 */
export const securityIdTypeEnumSchema: Schema<SecurityIdTypeEnum> = stringEnum(
  SecurityIdTypeEnum
);
