/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecuredEnum
 */
export enum SecuredEnum {
  COVERED = 'COVERED',
  NAKED = 'NAKED',
}

/**
 * Schema for SecuredEnum
 */
export const securedEnumSchema: Schema<SecuredEnum> = stringEnum(SecuredEnum);
