/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SecurityIdType3Enum
 */
export enum SecurityIdType3Enum {
  BUSIP = 'BUSIP',
  ISIN = 'ISIN',
  SEDOL = 'SEDOL',
  SICC = 'SICC',
  VALOR = 'VALOR',
  WKN = 'WKN',
}

/**
 * Schema for SecurityIdType3Enum
 */
export const securityIdType3EnumSchema: Schema<SecurityIdType3Enum> = stringEnum(
  SecurityIdType3Enum
);
