/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  LocalTaxWithholding1,
  localTaxWithholding1Schema,
} from './localTaxWithholding1';
import { StateCode2Enum, stateCode2EnumSchema } from './stateCode2Enum';
import {
  StateTaxWithholding2,
  stateTaxWithholding2Schema,
} from './stateTaxWithholding2';

/** Income in a state and/or locality and its or their tax withholding */
export interface StateAndLocalTaxWithholding {
  /** State two-digit code */
  stateCode?: StateCode2Enum;
  /** Amount of state income tax withheld */
  state?: StateTaxWithholding2;
  /** Amount of local income tax withheld, if any */
  local?: LocalTaxWithholding1;
}

export const stateAndLocalTaxWithholdingSchema: Schema<StateAndLocalTaxWithholding> = object(
  {
    stateCode: ['stateCode', optional(stateCode2EnumSchema)],
    state: ['state', optional(lazy(() => stateTaxWithholding2Schema))],
    local: ['local', optional(lazy(() => localTaxWithholding1Schema))],
  }
);
