/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StatusEnum
 */
export enum StatusEnum {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  PENDINGOPEN = 'PENDINGOPEN',
  PENDINGCLOSE = 'PENDINGCLOSE',
  DELINQUENT = 'DELINQUENT',
  PAID = 'PAID',
  NEGATIVECURRENTBALANCE = 'NEGATIVECURRENTBALANCE',
}

/**
 * Schema for StatusEnum
 */
export const statusEnumSchema: Schema<StatusEnum> = stringEnum(StatusEnum);
