/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Income in a state and its tax withholding */
export interface StateTaxWithholding {
  /** Amount of state income tax withheld */
  taxWithheld?: number;
  /** Filer's state tax id */
  taxId?: string;
  /** Income amount for state tax purposes */
  income?: number;
}

export const stateTaxWithholdingSchema: Schema<StateTaxWithholding> = object({
  taxWithheld: ['taxWithheld', optional(number())],
  taxId: ['taxId', optional(string())],
  income: ['income', optional(number())],
});
