/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Amount of state income tax withheld */
export interface StateTaxWithholding2 {
  /** Amount of state income tax withheld */
  taxWithheld?: number;
  /** Filer's state tax id */
  taxId?: string;
  /** Income amount for state tax purposes */
  income?: number;
}

export const stateTaxWithholding2Schema: Schema<StateTaxWithholding2> = object({
  taxWithheld: ['taxWithheld', optional(number())],
  taxId: ['taxId', optional(string())],
  income: ['income', optional(number())],
});
