/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, optional, Schema, string } from '../schema';
import { StockTypeEnum, stockTypeEnumSchema } from './stockTypeEnum';

/** Information about the stock security specific to the type of security */
export interface StockSecurityEntity {
  /** Units in the FI's street name, positive quantity */
  unitsStreet?: number;
  /** Units in user's name directly, positive  quantity */
  unitsUser?: number;
  /** Reinvest dividends */
  reinvestDividends?: boolean;
  stockType?: StockTypeEnum;
  /** Current yield */
  yield?: number;
  /** Yield as-of date */
  yieldAsOfDate?: string;
}

export const stockSecurityEntitySchema: Schema<StockSecurityEntity> = object({
  unitsStreet: ['unitsStreet', optional(number())],
  unitsUser: ['unitsUser', optional(number())],
  reinvestDividends: ['reinvestDividends', optional(boolean())],
  stockType: ['stockType', optional(stockTypeEnumSchema)],
  yield: ['yield', optional(number())],
  yieldAsOfDate: ['yieldAsOfDate', optional(string())],
});
