/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StockTypeEnum
 */
export enum StockTypeEnum {
  BOND = 'BOND',
  DEBT = 'DEBT',
  MUTUALFUND = 'MUTUALFUND',
  OPTION = 'OPTION',
  OTHER = 'OTHER',
  STOCK = 'STOCK',
  SWEEP = 'SWEEP',
}

/**
 * Schema for StockTypeEnum
 */
export const stockTypeEnumSchema: Schema<StockTypeEnum> = stringEnum(
  StockTypeEnum
);
