/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubAccountEnum
 */
export enum SubAccountEnum {
  CASH = 'CASH',
  MARGIN = 'MARGIN',
  SHORT = 'SHORT',
  OTHER = 'OTHER',
}

/**
 * Schema for SubAccountEnum
 */
export const subAccountEnumSchema: Schema<SubAccountEnum> = stringEnum(
  SubAccountEnum
);
