/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SubAccountSecEnum
 */
export enum SubAccountSecEnum {
  CASH = 'CASH',
  MARGIN = 'MARGIN',
  SHORT = 'SHORT',
  OTHERS = 'OTHERS',
}

/**
 * Schema for SubAccountSecEnum
 */
export const subAccountSecEnumSchema: Schema<SubAccountSecEnum> = stringEnum(
  SubAccountSecEnum
);
