/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  BusinessIncomeStatement,
  businessIncomeStatementSchema,
} from './businessIncomeStatement';
import {
  CryptocurrencyTaxStatementList1,
  cryptocurrencyTaxStatementList1Schema,
} from './cryptocurrencyTaxStatementList1';
import {
  FarmIncomeStatement,
  farmIncomeStatementSchema,
} from './farmIncomeStatement';
import {
  FarmRentalIncomeStatement,
  farmRentalIncomeStatementSchema,
} from './farmRentalIncomeStatement';
import { Form1041K1, form1041K1Schema } from './form1041K1';
import { Form1041K12, form1041K12Schema } from './form1041K12';
import { Form1042S2, form1042S2Schema } from './form1042S2';
import { Form1065K12, form1065K12Schema } from './form1065K12';
import { Form1095A2, form1095A2Schema } from './form1095A2';
import { Form1095B2, form1095B2Schema } from './form1095B2';
import { Form1095C2, form1095C2Schema } from './form1095C2';
import { Form1097BTC2, form1097BTC2Schema } from './form1097BTC2';
import { Form10982, form10982Schema } from './form10982';
import { Form1098C2, form1098C2Schema } from './form1098C2';
import { Form1098E2, form1098E2Schema } from './form1098E2';
import { Form1098MA2, form1098MA2Schema } from './form1098MA2';
import { Form1098Q2, form1098Q2Schema } from './form1098Q2';
import { Form1098T2, form1098T2Schema } from './form1098T2';
import { Form1099A2, form1099A2Schema } from './form1099A2';
import { Form1099B2, form1099B2Schema } from './form1099B2';
import { Form1099C2, form1099C2Schema } from './form1099C2';
import { Form1099CAP2, form1099CAP2Schema } from './form1099CAP2';
import {
  Form1099ConsolidatedStatement2,
  form1099ConsolidatedStatement2Schema,
} from './form1099ConsolidatedStatement2';
import { Form1099DIV2, form1099DIV2Schema } from './form1099DIV2';
import { Form1099G2, form1099G2Schema } from './form1099G2';
import { Form1099H2, form1099H2Schema } from './form1099H2';
import { Form1099INT2, form1099INT2Schema } from './form1099INT2';
import { Form1099K2, form1099K2Schema } from './form1099K2';
import { Form1099LS2, form1099LS2Schema } from './form1099LS2';
import { Form1099LTC2, form1099LTC2Schema } from './form1099LTC2';
import { Form1099MISC2, form1099MISC2Schema } from './form1099MISC2';
import { Form1099NEC2, form1099NEC2Schema } from './form1099NEC2';
import { Form1099OID2, form1099OID2Schema } from './form1099OID2';
import { Form1099PATR2, form1099PATR2Schema } from './form1099PATR2';
import { Form1099Q2, form1099Q2Schema } from './form1099Q2';
import { Form1099QA2, form1099QA2Schema } from './form1099QA2';
import { Form1099R2, form1099R2Schema } from './form1099R2';
import { Form1099S2, form1099S2Schema } from './form1099S2';
import { Form1099SA2, form1099SA2Schema } from './form1099SA2';
import { Form1099SB2, form1099SB2Schema } from './form1099SB2';
import { Form1120SK12, form1120SK12Schema } from './form1120SK12';
import { Form24392, form24392Schema } from './form24392';
import { Form39212, form39212Schema } from './form39212';
import { Form39222, form39222Schema } from './form39222';
import { Form54982, form54982Schema } from './form54982';
import { Form5498ESA2, form5498ESA2Schema } from './form5498ESA2';
import { Form5498QA2, form5498QA2Schema } from './form5498QA2';
import { Form5498SA2, form5498SA2Schema } from './form5498SA2';
import { FormW24, formW24Schema } from './formW24';
import { FormW2c2, formW2c2Schema } from './formW2c2';
import { FormW2G2, formW2G2Schema } from './formW2G2';
import {
  RentalIncomeStatement,
  rentalIncomeStatementSchema,
} from './rentalIncomeStatement';
import {
  RoyaltyIncomeStatement,
  royaltyIncomeStatementSchema,
} from './royaltyIncomeStatement';
import {
  TaxRefundDirectDeposit2,
  taxRefundDirectDeposit2Schema,
} from './taxRefundDirectDeposit2';

/** Tax data container for API requests and responses */
export interface TaxData {
  /** Business Income Statement for IRS Form 1040 Schedule C */
  businessIncomeStatement?: BusinessIncomeStatement;
  /** Cryptocurrency Tax Statement list */
  cryptocurrencyTaxStatement?: CryptocurrencyTaxStatementList1;
  /** Farm Income Statement for IRS Form 1040 Schedule F */
  farmIncomeStatement?: FarmIncomeStatement;
  /** Farm Rental Income Statement for IRS Form 4835 */
  farmRentalIncomeStatement?: FarmRentalIncomeStatement;
  /** Rental Income Statement for IRS Form 1040 Schedule E */
  rentalIncomeStatement?: RentalIncomeStatement;
  /** Royalty Income Statement for IRS Form 1040 Schedule E */
  royaltyIncomeStatement?: RoyaltyIncomeStatement;
  /** Beneficiary's Share of Income, Deductions, Credits, etc. */
  tax1041K1?: Form1041K12;
  /** Foreign Person's U.S. Source Income Subject to Withholding */
  tax1042S?: Form1042S2;
  /** Partner's Share of Income, Deductions, Credits, etc. */
  tax1065K1?: Form1065K12;
  /** Health Insurance Marketplace Statement */
  tax1095A?: Form1095A2;
  /** Health Coverage */
  tax1095B?: Form1095B2;
  /** Employer-Provided Health Insurance Offer and Coverage */
  tax1095C?: Form1095C2;
  /** Bond Tax Credit */
  tax1097Btc?: Form1097BTC2;
  /** Mortgage Interest Statement */
  tax1098?: Form10982;
  /** Contributions of Motor Vehicles, Boats, and Airplanes */
  tax1098C?: Form1098C2;
  /** Student Loan Interest Statement */
  tax1098E?: Form1098E2;
  /** Mortgage Assistance Payments */
  tax1098Ma?: Form1098MA2;
  /** Qualifying Longevity Annuity Contract Information */
  tax1098Q?: Form1098Q2;
  /** Tuition Statement */
  tax1098T?: Form1098T2;
  /** Acquisition or Abandonment of Secured Property */
  tax1099A?: Form1099A2;
  /** Proceeds From Broker and Barter Exchange Transactions */
  tax1099B?: Form1099B2;
  /** Cancellation of Debt */
  tax1099C?: Form1099C2;
  /** Changes in Corporate Control and Capital Structure */
  tax1099Cap?: Form1099CAP2;
  /** Consolidated Statement for combined IRS Form 1099s */
  tax1099ConsolidatedStatement?: Form1099ConsolidatedStatement2;
  /** Dividends and Distributions */
  tax1099Div?: Form1099DIV2;
  /** Certain Government Payments */
  tax1099G?: Form1099G2;
  /** Health Coverage Tax Credit (HCTC) Advance Payments */
  tax1099H?: Form1099H2;
  /** Interest Income */
  tax1099Int?: Form1099INT2;
  /** Merchant Card and Third-Party Network Payments */
  tax1099K?: Form1099K2;
  /** Reportable Life Insurance Sale */
  tax1099Ls?: Form1099LS2;
  /** Long-Term Care and Accelerated Death Benefits */
  tax1099Ltc?: Form1099LTC2;
  /** Miscellaneous Income */
  tax1099Misc?: Form1099MISC2;
  /** Nonemployee Compensation */
  tax1099Nec?: Form1099NEC2;
  /** Original Issue Discount */
  tax1099Oid?: Form1099OID2;
  /** Taxable Distributions Received From Cooperatives */
  tax1099Patr?: Form1099PATR2;
  /** Payments From Qualified Education Programs */
  tax1099Q?: Form1099Q2;
  /** Distributions From ABLE Accounts */
  tax1099Qa?: Form1099QA2;
  /** Distributions from Pensions, Annuities, Retirement or Profit-Sharing Plans, IRAs, Insurance Contracts, etc. */
  tax1099R?: Form1099R2;
  /** Proceeds From Real Estate Transactions */
  tax1099S?: Form1099S2;
  /** Distributions From an HSA, Archer MSA, or Medicare Advantage MSA */
  tax1099Sa?: Form1099SA2;
  /** Seller's Investment in Life Insurance Contract */
  tax1099Sb?: Form1099SB2;
  /** Shareholder's Share of Income, Deductions, Credits, etc. */
  tax1120SK1?: Form1120SK12;
  /** Notice to Shareholder of Undistributed Long-Term Capital Gains */
  tax2439?: Form24392;
  /** Exercise of an Incentive Stock Option Under Section 422(b) */
  tax3921?: Form39212;
  /** Transfer of Stock Acquired Through an Employee Stock Purchase Plan under Section 423(c) */
  tax3922?: Form39222;
  /** Split-Interest Trust Beneficiary's schedule K-1 */
  tax5227K1?: Form1041K1;
  /** IRA Contribution Information */
  tax5498?: Form54982;
  /** Coverdell ESA Contribution Information */
  tax5498Esa?: Form5498ESA2;
  /** ABLE Account Contribution Information */
  tax5498Qa?: Form5498QA2;
  /** HSA, Archer MSA, or Medicare Advantage MSA Information */
  tax5498Sa?: Form5498SA2;
  /** Wage and Tax Statement */
  taxW2?: FormW24;
  /** IRS form W-2c, Corrected Wage and Tax Statement */
  taxW2C?: FormW2c2;
  /** Certain Gambling Winnings */
  taxW2G?: FormW2G2;
  /** Tax refund direct deposit information */
  taxRefundDirectDeposit?: TaxRefundDirectDeposit2;
}

export const taxDataSchema: Schema<TaxData> = object({
  businessIncomeStatement: [
    'businessIncomeStatement',
    optional(lazy(() => businessIncomeStatementSchema)),
  ],
  cryptocurrencyTaxStatement: [
    'cryptocurrencyTaxStatement',
    optional(lazy(() => cryptocurrencyTaxStatementList1Schema)),
  ],
  farmIncomeStatement: [
    'farmIncomeStatement',
    optional(lazy(() => farmIncomeStatementSchema)),
  ],
  farmRentalIncomeStatement: [
    'farmRentalIncomeStatement',
    optional(lazy(() => farmRentalIncomeStatementSchema)),
  ],
  rentalIncomeStatement: [
    'rentalIncomeStatement',
    optional(lazy(() => rentalIncomeStatementSchema)),
  ],
  royaltyIncomeStatement: [
    'royaltyIncomeStatement',
    optional(lazy(() => royaltyIncomeStatementSchema)),
  ],
  tax1041K1: ['tax1041K1', optional(lazy(() => form1041K12Schema))],
  tax1042S: ['tax1042S', optional(lazy(() => form1042S2Schema))],
  tax1065K1: ['tax1065K1', optional(lazy(() => form1065K12Schema))],
  tax1095A: ['tax1095A', optional(lazy(() => form1095A2Schema))],
  tax1095B: ['tax1095B', optional(lazy(() => form1095B2Schema))],
  tax1095C: ['tax1095C', optional(lazy(() => form1095C2Schema))],
  tax1097Btc: ['tax1097Btc', optional(lazy(() => form1097BTC2Schema))],
  tax1098: ['tax1098', optional(lazy(() => form10982Schema))],
  tax1098C: ['tax1098C', optional(lazy(() => form1098C2Schema))],
  tax1098E: ['tax1098E', optional(lazy(() => form1098E2Schema))],
  tax1098Ma: ['tax1098Ma', optional(lazy(() => form1098MA2Schema))],
  tax1098Q: ['tax1098Q', optional(lazy(() => form1098Q2Schema))],
  tax1098T: ['tax1098T', optional(lazy(() => form1098T2Schema))],
  tax1099A: ['tax1099A', optional(lazy(() => form1099A2Schema))],
  tax1099B: ['tax1099B', optional(lazy(() => form1099B2Schema))],
  tax1099C: ['tax1099C', optional(lazy(() => form1099C2Schema))],
  tax1099Cap: ['tax1099Cap', optional(lazy(() => form1099CAP2Schema))],
  tax1099ConsolidatedStatement: [
    'tax1099ConsolidatedStatement',
    optional(lazy(() => form1099ConsolidatedStatement2Schema)),
  ],
  tax1099Div: ['tax1099Div', optional(lazy(() => form1099DIV2Schema))],
  tax1099G: ['tax1099G', optional(lazy(() => form1099G2Schema))],
  tax1099H: ['tax1099H', optional(lazy(() => form1099H2Schema))],
  tax1099Int: ['tax1099Int', optional(lazy(() => form1099INT2Schema))],
  tax1099K: ['tax1099K', optional(lazy(() => form1099K2Schema))],
  tax1099Ls: ['tax1099Ls', optional(lazy(() => form1099LS2Schema))],
  tax1099Ltc: ['tax1099Ltc', optional(lazy(() => form1099LTC2Schema))],
  tax1099Misc: ['tax1099Misc', optional(lazy(() => form1099MISC2Schema))],
  tax1099Nec: ['tax1099Nec', optional(lazy(() => form1099NEC2Schema))],
  tax1099Oid: ['tax1099Oid', optional(lazy(() => form1099OID2Schema))],
  tax1099Patr: ['tax1099Patr', optional(lazy(() => form1099PATR2Schema))],
  tax1099Q: ['tax1099Q', optional(lazy(() => form1099Q2Schema))],
  tax1099Qa: ['tax1099Qa', optional(lazy(() => form1099QA2Schema))],
  tax1099R: ['tax1099R', optional(lazy(() => form1099R2Schema))],
  tax1099S: ['tax1099S', optional(lazy(() => form1099S2Schema))],
  tax1099Sa: ['tax1099Sa', optional(lazy(() => form1099SA2Schema))],
  tax1099Sb: ['tax1099Sb', optional(lazy(() => form1099SB2Schema))],
  tax1120SK1: ['tax1120SK1', optional(lazy(() => form1120SK12Schema))],
  tax2439: ['tax2439', optional(lazy(() => form24392Schema))],
  tax3921: ['tax3921', optional(lazy(() => form39212Schema))],
  tax3922: ['tax3922', optional(lazy(() => form39222Schema))],
  tax5227K1: ['tax5227K1', optional(lazy(() => form1041K1Schema))],
  tax5498: ['tax5498', optional(lazy(() => form54982Schema))],
  tax5498Esa: ['tax5498Esa', optional(lazy(() => form5498ESA2Schema))],
  tax5498Qa: ['tax5498Qa', optional(lazy(() => form5498QA2Schema))],
  tax5498Sa: ['tax5498Sa', optional(lazy(() => form5498SA2Schema))],
  taxW2: ['taxW2', optional(lazy(() => formW24Schema))],
  taxW2C: ['taxW2C', optional(lazy(() => formW2c2Schema))],
  taxW2G: ['taxW2G', optional(lazy(() => formW2G2Schema))],
  taxRefundDirectDeposit: [
    'taxRefundDirectDeposit',
    optional(lazy(() => taxRefundDirectDeposit2Schema)),
  ],
});
