/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** An additional tax form attribute for use when a defined field is not available */
export interface TaxFormAttribute {
  /** Name of attribute */
  name?: string;
  /** Value of attribute */
  value?: string;
  /** Box number on a tax form, if any */
  boxNumber?: string;
  /** Tax form code for the given box number, if any */
  code?: string;
}

export const taxFormAttributeSchema: Schema<TaxFormAttribute> = object({
  name: ['name', optional(string())],
  value: ['value', optional(string())],
  boxNumber: ['boxNumber', optional(string())],
  code: ['code', optional(string())],
});
