/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Holding, holdingSchema } from './holding';

export interface TaxlotsResponse {
  /** Corresponds to AccountId in Account */
  accountId?: string;
  holding?: Holding;
}

export const taxlotsResponseSchema: Schema<TaxlotsResponse> = object({
  accountId: ['accountId', optional(string())],
  holding: ['holding', optional(lazy(() => holdingSchema))],
});
