/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  PositionType2Enum,
  positionType2EnumSchema,
} from './positionType2Enum';

export interface TaxLot1 {
  /** Total amount of money spent acquiring this lot including any fees or commission expenses incurred. */
  costBasis?: number;
  /** Lot market value */
  currentValue?: number;
  /** Lot acquired date. */
  originalPurchaseDate?: string;
  /** LONG, SHORT. */
  positionType?: PositionType2Enum;
  /** Original purchase price. */
  purchasedPrice?: number;
  /** Lot quantity. */
  quantity?: number;
}

export const taxLot1Schema: Schema<TaxLot1> = object({
  costBasis: ['costBasis', optional(number())],
  currentValue: ['currentValue', optional(number())],
  originalPurchaseDate: ['originalPurchaseDate', optional(string())],
  positionType: ['positionType', optional(positionType2EnumSchema)],
  purchasedPrice: ['purchasedPrice', optional(number())],
  quantity: ['quantity', optional(number())],
});
