/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Holding1, holding1Schema } from './holding1';

export interface TaxlotsAccountIdHoldingIdResponse {
  accountId?: string;
  holding?: Holding1;
}

export const taxlotsAccountIdHoldingIdResponseSchema: Schema<TaxlotsAccountIdHoldingIdResponse> = object(
  {
    accountId: ['accountId', optional(string())],
    holding: ['holding', optional(lazy(() => holding1Schema))],
  }
);
