/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { PostionTypeEnum, postionTypeEnumSchema } from './postionTypeEnum';

export interface TaxLot {
  /** Total amount of money spent acquiring this lot including any fees or commission expenses incurred. */
  costBasis?: number;
  /** Lot market value */
  currentValue?: number;
  /** Lot acquired date. */
  originalPurchaseDate?: string;
  /** LONG, SHORT. */
  postionType?: PostionTypeEnum;
  /** Original purchase price. */
  purchasedPrice?: number;
  /** Lot quantity. */
  quantity?: number;
}

export const taxLotSchema: Schema<TaxLot> = object({
  costBasis: ['costBasis', optional(number())],
  currentValue: ['currentValue', optional(number())],
  originalPurchaseDate: ['originalPurchaseDate', optional(string())],
  postionType: ['postionType', optional(postionTypeEnumSchema)],
  purchasedPrice: ['purchasedPrice', optional(number())],
  quantity: ['quantity', optional(number())],
});
