/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface TaxLot2 {
  originalPurchaseDate?: string;
  quantity?: number;
  purchasedPrice?: number;
  costBasis?: number;
  currentValue?: number;
  positionType?: string;
}

export const taxLot2Schema: Schema<TaxLot2> = object({
  originalPurchaseDate: ['originalPurchaseDate', optional(string())],
  quantity: ['quantity', optional(number())],
  purchasedPrice: ['purchasedPrice', optional(number())],
  costBasis: ['costBasis', optional(number())],
  currentValue: ['currentValue', optional(number())],
  positionType: ['positionType', optional(string())],
});
