/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxPartyTypeEnum
 */
export enum TaxPartyTypeEnum {
  BUSINESS = 'BUSINESS',
  INDIVIDUAL = 'INDIVIDUAL',
}

/**
 * Schema for TaxPartyTypeEnum
 */
export const taxPartyTypeEnumSchema: Schema<TaxPartyTypeEnum> = stringEnum(
  TaxPartyTypeEnum
);
