/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxPartyType2Enum
 */
export enum TaxPartyType2Enum {
  BUSINESS = 'BUSINESS',
  INDIVIDUAL = 'INDIVIDUAL',
}

/**
 * Schema for TaxPartyType2Enum
 */
export const taxPartyType2EnumSchema: Schema<TaxPartyType2Enum> = stringEnum(
  TaxPartyType2Enum
);
