/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Address1, address1Schema } from './address1';
import { BusinessName1, businessName1Schema } from './businessName1';
import { IndividualName4, individualName4Schema } from './individualName4';
import {
  TaxPartyType2Enum,
  taxPartyType2EnumSchema,
} from './taxPartyType2Enum';
import {
  TelephoneNumberPlusExtension4,
  telephoneNumberPlusExtension4Schema,
} from './telephoneNumberPlusExtension4';

/** Legal entity for issuer or recipient, used across all tax forms */
export interface TaxParty {
  /** Issuer or recipient Tax Identification Number. Usually EIN for issuer and SSN for recipient */
  tin?: string;
  /** Type of issuer or recipient legal entity, as "BUSINESS" or "INDIVIDUAL". Commonly BUSINESS for issuer and INDIVIDUAL for recipient */
  partyType?: TaxPartyType2Enum;
  /** Individual issuer or recipient name */
  individualName?: IndividualName4;
  /** Business issuer or recipient name */
  businessName?: BusinessName1;
  /** Issuer or recipient address */
  address?: Address1;
  /** Issuer or recipient telephone number */
  phone?: TelephoneNumberPlusExtension4;
  /** Issuer or recipient email address. (Additional information, not part of IRS forms) */
  email?: string;
}

export const taxPartySchema: Schema<TaxParty> = object({
  tin: ['tin', optional(string())],
  partyType: ['partyType', optional(taxPartyType2EnumSchema)],
  individualName: [
    'individualName',
    optional(lazy(() => individualName4Schema)),
  ],
  businessName: ['businessName', optional(lazy(() => businessName1Schema))],
  address: ['address', optional(lazy(() => address1Schema))],
  phone: ['phone', optional(lazy(() => telephoneNumberPlusExtension4Schema))],
  email: ['email', optional(string())],
});
