/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Tax refund direct deposit information */
export interface TaxRefundDirectDeposit2 {
  /** Name of institution */
  institutionName?: string;
  /** Routing transit number */
  rtn?: string;
  /** Account number */
  accountNumber?: string;
  /** Account nickname */
  accountNickName?: string;
}

export const taxRefundDirectDeposit2Schema: Schema<TaxRefundDirectDeposit2> = object(
  {
    institutionName: ['institutionName', optional(string())],
    rtn: ['rtn', optional(string())],
    accountNumber: ['accountNumber', optional(string())],
    accountNickName: ['accountNickName', optional(string())],
  }
);
