/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { TaxStatement, taxStatementSchema } from './taxStatement';

/** Tax statement list containing one or more tax statements */
export interface TaxStatementList {
  /** The list of tax statements */
  statements?: TaxStatement[];
}

export const taxStatementListSchema: Schema<TaxStatementList> = object({
  statements: ['statements', optional(array(lazy(() => taxStatementSchema)))],
});
