/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  FiAttributeEntity,
  fiAttributeEntitySchema,
} from './fiAttributeEntity';
import { TaxData, taxDataSchema } from './taxData';
import { TaxParty6, taxParty6Schema } from './taxParty6';
import { TaxParty7, taxParty7Schema } from './taxParty7';
import {
  TypeDataType1Enum,
  typeDataType1EnumSchema,
} from './typeDataType1Enum';

/** The TaxStatement json for a single tax document containing one or more tax reporting forms for the customer */
export interface TaxStatement1 {
  /** Year for which taxes are being paid */
  taxYear?: number;
  /** Long-term persistent id for the tax statement. Depending upon the data provider, this may be the same id as the id on the enclosed tax form(s), or this may be a different id */
  taxStatementId?: string;
  /** Issuer's name, address, phone, and TIN. Issuer data need only be transmittted on TaxStatement, 'JSON' data type responses if it is the same on all included tax forms */
  issuer?: TaxParty6;
  /** Recipient's name, address, phone, and TIN. Recipient data need only be transmittted on TaxStatement, 'JSON' data type responses if it is the same on all included tax forms */
  recipient?: TaxParty7;
  /** Whether this `application/json` tax form response contains data in `forms` property (as 'JSON' format) or `pdf` property (as 'BASE64_PDF' format) */
  taxDataType?: TypeDataType1Enum;
  /** The list of data contents for all included tax forms, response should include one of `forms` or `pdf` */
  forms?: TaxData[];
  /** PDF version of the tax statement containing all form pages, binary encoded as Base64, response should include one of `pdf` or `forms` */
  pdf?: string;
  /** Additional tax statement attributes that the provider wishes to include */
  attributes?: FiAttributeEntity[];
}

export const taxStatement1Schema: Schema<TaxStatement1> = object({
  taxYear: ['taxYear', optional(number())],
  taxStatementId: ['taxStatementId', optional(string())],
  issuer: ['issuer', optional(lazy(() => taxParty6Schema))],
  recipient: ['recipient', optional(lazy(() => taxParty7Schema))],
  taxDataType: ['taxDataType', optional(typeDataType1EnumSchema)],
  forms: ['forms', optional(array(lazy(() => taxDataSchema)))],
  pdf: ['pdf', optional(string())],
  attributes: [
    'attributes',
    optional(array(lazy(() => fiAttributeEntitySchema))),
  ],
});
