/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TelephoneNumberType2Enum
 */
export enum TelephoneNumberType2Enum {
  BUSINESS = 'BUSINESS',
  CELL = 'CELL',
  FAX = 'FAX',
  HOME = 'HOME',
}

/**
 * Schema for TelephoneNumberType2Enum
 */
export const telephoneNumberType2EnumSchema: Schema<TelephoneNumberType2Enum> = stringEnum(
  TelephoneNumberType2Enum
);
