/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  TelephoneNumberType2Enum,
  telephoneNumberType2EnumSchema,
} from './telephoneNumberType2Enum';

/** Standard for international phone numbers */
export interface TelephoneNumber {
  /** Type of phone number: HOME, BUSINESS, CELL, FAX */
  type?: TelephoneNumberType2Enum;
  /** Country calling codes defined by ITU-T recommendations E.123 and E.164 */
  country?: string;
  /** Telephone subscriber number defined by ITU-T recommendation E.164 */
  number?: string;
}

export const telephoneNumberSchema: Schema<TelephoneNumber> = object({
  type: ['type', optional(telephoneNumberType2EnumSchema)],
  country: ['country', optional(string())],
  number: ['number', optional(string())],
});
