/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type2Enum, type2EnumSchema } from './type2Enum';

export interface Telephone {
  number?: string;
  type?: Type2Enum;
  /** Country calling codes defined by ITU-T recommendations E.123 and E.164 */
  country?: string;
}

export const telephoneSchema: Schema<Telephone> = object({
  number: ['number', optional(string())],
  type: ['type', optional(type2EnumSchema)],
  country: ['country', optional(string())],
});
