/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TelephoneNumberTypeEnum
 */
export enum TelephoneNumberTypeEnum {
  BUSINESS = 'BUSINESS',
  CELL = 'CELL',
  FAX = 'FAX',
  HOME = 'HOME',
}

/**
 * Schema for TelephoneNumberTypeEnum
 */
export const telephoneNumberTypeEnumSchema: Schema<TelephoneNumberTypeEnum> = stringEnum(
  TelephoneNumberTypeEnum
);
