/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionType1Enum
 */
export enum TransactionType1Enum {
  PAYMENT = 'PAYMENT',
  FEE = 'FEE',
  ADJUSTMENT = 'ADJUSTMENT',
  INTEREST = 'INTEREST',
}

/**
 * Schema for TransactionType1Enum
 */
export const transactionType1EnumSchema: Schema<TransactionType1Enum> = stringEnum(
  TransactionType1Enum
);
