/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InvestmentTransaction,
  investmentTransactionSchema,
} from './investmentTransaction';

export interface Transaction13 {
  /** Investment Transactions */
  investmentTransaction?: InvestmentTransaction;
}

export const transaction13Schema: Schema<Transaction13> = object({
  investmentTransaction: [
    'investmentTransaction',
    optional(lazy(() => investmentTransactionSchema)),
  ],
});
