/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionReasonEnum
 */
export enum TransactionReasonEnum {
  CALL = 'CALL',
  SELL = 'SELL',
  MATURITY = 'MATURITY',
}

/**
 * Schema for TransactionReasonEnum
 */
export const transactionReasonEnumSchema: Schema<TransactionReasonEnum> = stringEnum(
  TransactionReasonEnum
);
