/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionTypeEnum
 */
export enum TransactionTypeEnum {
  CHECK = 'CHECK',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
  POSDEBIT = 'POSDEBIT',
  ATMWITHDRAWAL = 'ATMWITHDRAWAL',
  BILLPAYMENT = 'BILLPAYMENT',
  FEE = 'FEE',
  DEPOSIT = 'DEPOSIT',
  ADJUSTMENT = 'ADJUSTMENT',
  INTEREST = 'INTEREST',
  DIVIDEND = 'DIVIDEND',
  DIRECTDEPOSIT = 'DIRECTDEPOSIT',
  ATMDEPOSIT = 'ATMDEPOSIT',
  POSCREDIT = 'POSCREDIT',
}

/**
 * Schema for TransactionTypeEnum
 */
export const transactionTypeEnumSchema: Schema<TransactionTypeEnum> = stringEnum(
  TransactionTypeEnum
);
