/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  DepositTransaction,
  depositTransactionSchema,
} from './depositTransaction';

export interface Transaction1 {
  /** Deposit transaction */
  depositTransaction?: DepositTransaction;
}

export const transaction1Schema: Schema<Transaction1> = object({
  depositTransaction: [
    'depositTransaction',
    optional(lazy(() => depositTransactionSchema)),
  ],
});
