/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LoanTransaction, loanTransactionSchema } from './loanTransaction';

export interface Transaction11 {
  /** Loan Transaction */
  loanTransaction?: LoanTransaction;
}

export const transaction11Schema: Schema<Transaction11> = object({
  loanTransaction: [
    'loanTransaction',
    optional(lazy(() => loanTransactionSchema)),
  ],
});
