/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  InsuranceTransaction,
  insuranceTransactionSchema,
} from './insuranceTransaction';

export interface Transaction14 {
  /** Insurance transactions */
  insuranceTransaction?: InsuranceTransaction;
}

export const transaction14Schema: Schema<Transaction14> = object({
  insuranceTransaction: [
    'insuranceTransaction',
    optional(lazy(() => insuranceTransactionSchema)),
  ],
});
