/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  DepositTransaction,
  depositTransactionSchema,
} from './depositTransaction';
import {
  InsuranceTransaction,
  insuranceTransactionSchema,
} from './insuranceTransaction';
import {
  InvestmentTransaction,
  investmentTransactionSchema,
} from './investmentTransaction';
import { LoanTransaction, loanTransactionSchema } from './loanTransaction';
import { LocTransaction, locTransactionSchema } from './locTransaction';

export interface Transaction15 {
  /** Deposit transaction */
  depositTransaction?: DepositTransaction;
  /** Loan Transaction */
  loanTransaction?: LoanTransaction;
  /** A line of credit transaction of type */
  locTransaction?: LocTransaction;
  /** Investment Transactions */
  investmentTransaction?: InvestmentTransaction;
  /** Insurance transactions */
  insuranceTransaction?: InsuranceTransaction;
}

export const transaction15Schema: Schema<Transaction15> = object({
  depositTransaction: [
    'depositTransaction',
    optional(lazy(() => depositTransactionSchema)),
  ],
  loanTransaction: [
    'loanTransaction',
    optional(lazy(() => loanTransactionSchema)),
  ],
  locTransaction: [
    'locTransaction',
    optional(lazy(() => locTransactionSchema)),
  ],
  investmentTransaction: [
    'investmentTransaction',
    optional(lazy(() => investmentTransactionSchema)),
  ],
  insuranceTransaction: [
    'insuranceTransaction',
    optional(lazy(() => insuranceTransactionSchema)),
  ],
});
