/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionType3Enum
 */
export enum TransactionType3Enum {
  ADJUSTMENT = 'ADJUSTMENT',
  FEE = 'FEE',
  INTEREST = 'INTEREST',
  PAYMENT = 'PAYMENT',
}

/**
 * Schema for TransactionType3Enum
 */
export const transactionType3EnumSchema: Schema<TransactionType3Enum> = stringEnum(
  TransactionType3Enum
);
