/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransferActionEnum
 */
export enum TransferActionEnum {
  IN = 'IN',
  OUT = 'OUT',
}

/**
 * Schema for TransferActionEnum
 */
export const transferActionEnumSchema: Schema<TransferActionEnum> = stringEnum(
  TransferActionEnum
);
