/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { LocTransaction, locTransactionSchema } from './locTransaction';

export interface Transaction12 {
  /** A line of credit transaction of type */
  locTransaction?: LocTransaction;
}

export const transaction12Schema: Schema<Transaction12> = object({
  locTransaction: [
    'locTransaction',
    optional(lazy(() => locTransactionSchema)),
  ],
});
