/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  EnumApplicationpdf = 'application/pdf',
  EnumImagegif = 'image/gif',
  EnumImagejpeg = 'image/jpeg',
  EnumImagetiff = 'image/tiff',
  EnumImagepng = 'image/png',
  EnumApplicationjson = 'application/json',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
