/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeDataTypeEnum
 */
export enum TypeDataTypeEnum {
  BASE64PDF = 'BASE64_PDF',
  JSON = 'JSON',
}

/**
 * Schema for TypeDataTypeEnum
 */
export const typeDataTypeEnumSchema: Schema<TypeDataTypeEnum> = stringEnum(
  TypeDataTypeEnum
);
