/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeDataType1Enum
 */
export enum TypeDataType1Enum {
  BASE64PDF = 'BASE64_PDF',
  JSON = 'JSON',
}

/**
 * Schema for TypeDataType1Enum
 */
export const typeDataType1EnumSchema: Schema<TypeDataType1Enum> = stringEnum(
  TypeDataType1Enum
);
