/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnitType1Enum
 */
export enum UnitType1Enum {
  SHARES = 'SHARES',
  CURRENCY = 'CURRENCY',
}

/**
 * Schema for UnitType1Enum
 */
export const unitType1EnumSchema: Schema<UnitType1Enum> = stringEnum(
  UnitType1Enum
);
