/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnitTypeEnum
 */
export enum UnitTypeEnum {
  CURRENCY = 'CURRENCY',
  SHARES = 'SHARES',
}

/**
 * Schema for UnitTypeEnum
 */
export const unitTypeEnumSchema: Schema<UnitTypeEnum> = stringEnum(
  UnitTypeEnum
);
