/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VersionEnum
 */
export enum VersionEnum {
  V2 = 'v2',
}

/**
 * Schema for VersionEnum
 */
export const versionEnumSchema: Schema<VersionEnum> = stringEnum(VersionEnum);
