/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

/** Provides the past, present, and future vesting schedule and percentages. */
export interface VestingEntity {
  /** Vesting date */
  vestingDate?: string;
  /** Security symbol */
  symbol?: string;
  /** Strike price */
  strikePrice?: number;
  /** Vesting percentage */
  vestingPercentage?: number;
  /** Other vest amount */
  otherVestAmount?: number;
  /** Other vest percentage */
  otherVestPercentage?: number;
  /** Vested balance */
  vestedBalance?: number;
  /** Unvested balance */
  unVestedBalance?: number;
  /** Vested qualtity */
  vestedQuantity?: number;
  /** Unvested quantity */
  unVestedQuantity?: number;
}

export const vestingEntitySchema: Schema<VestingEntity> = object({
  vestingDate: ['vestingDate', optional(string())],
  symbol: ['symbol', optional(string())],
  strikePrice: ['strikePrice', optional(number())],
  vestingPercentage: ['vestingPercentage', optional(number())],
  otherVestAmount: ['otherVestAmount', optional(number())],
  otherVestPercentage: ['otherVestPercentage', optional(number())],
  vestedBalance: ['vestedBalance', optional(number())],
  unVestedBalance: ['unVestedBalance', optional(number())],
  vestedQuantity: ['vestedQuantity', optional(number())],
  unVestedQuantity: ['unVestedQuantity', optional(number())],
});
