/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for XAkoyaInteractionTypeEnum
 */
export enum XAkoyaInteractionTypeEnum {
  User = 'user',
  Batch = 'batch',
}

/**
 * Schema for XAkoyaInteractionTypeEnum
 */
export const xAkoyaInteractionTypeEnumSchema: Schema<XAkoyaInteractionTypeEnum> = stringEnum(
  XAkoyaInteractionTypeEnum
);
