/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  type Tool,
  type CallToolResult,
} from '@modelcontextprotocol/sdk/types.js';
import { accountInformationGetAccountsInfoTool } from './accountInformation/getAccountsInfo.js';
import { balancesGetBalancesTool } from './balances/getBalances.js';
import { customersCustomerInfoTool } from './customers/customerInfo.js';
import { customersGetAccountHolderTool } from './customers/getAccountHolder.js';
import { investmentsGetAccountsTool } from './investments/getAccounts.js';
import { investmentsGetTaxlotsTool } from './investments/getTaxlots.js';
import { paymentsPaymentNetworksTool } from './payments/paymentNetworks.js';
import { statementsGetStatementListTool } from './statements/getStatementList.js';
import { statementsGetStatementsTool } from './statements/getStatements.js';
import { taxGetTaxFormTool } from './tax/getTaxForm.js';
import { taxTaxFormsSearchTool } from './tax/taxFormsSearch.js';
import { transactionsGetTransactionsTool } from './transactions/getTransactions.js';


export type ToolDefinition = {
  tool: Tool;
  handler: (arg: unknown) => Promise<CallToolResult>;
};

// Export all defined tools in an array
export async function getAllTools(): Promise<Record<string, ToolDefinition>> {
  const tools =   [
    accountInformationGetAccountsInfoTool(),
    balancesGetBalancesTool(),
    customersCustomerInfoTool(),
    customersGetAccountHolderTool(),
    investmentsGetAccountsTool(),
    investmentsGetTaxlotsTool(),
    paymentsPaymentNetworksTool(),
    statementsGetStatementListTool(),
    statementsGetStatementsTool(),
    taxTaxFormsSearchTool(),
    taxGetTaxFormTool(),
    transactionsGetTransactionsTool(),
  ];

  const resolvedTools = await Promise.all(tools);

  const toolMap: Record<string, ToolDefinition> = {};
  for (const toolDef of resolvedTools) {
    toolMap[toolDef.tool.name] = toolDef;
  }
  return toolMap;
}
