/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type AnArrayOfStatements,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { statementsController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetStatementListMCPToolRequest {
  'accountId': string,
  'version': string,
  'providerId': string,
  'startTime': string,
  'endTime': string,
  'offset': string,
  'limit': number,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
}

async function executeGetStatementList(
  req: GetStatementListMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await statementsController.getStatementList(
      req['accountId'],
      req['version'],
      req['providerId'],
      req['startTime'],
      req['endTime'],
      req['offset'],
      req['limit'],
      req['x-akoya-interaction-type']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetStatementList(
  args: unknown | GetStatementListMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Statements", "get-statement-list");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getStatementList tool." }],
      isError: true,
    };
  }

  return await executeGetStatementList(args as GetStatementListMCPToolRequest);
}

export async function statementsGetStatementListTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "statements-getStatementList",
      description: `Retrieve a list of available statements for the end-user's consented accounts. You may request a date range of up to two years of historical statements (maximum date ranges vary by provider).

The paginated response includes an array of statement information with the end-user's account id and statement details such as statement id, date, description, and status. The results also include links to GET the statement image.`,
      inputSchema: await schemas.loadSchema("Statements", "get-statement-list"),
    },
    handler: handleGetStatementList,
  };
}

