/**
 * Akoya APIs v2.4.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  ApiError,
  type XAkoyaInteractionTypeEnum,
} from 'akoya-apis-v-2-4-0-lib';
import { schemas } from '../../schema.js';
import { statementsController } from '../../sdk-client.js';
import { stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetStatementsMCPToolRequest {
  'accountId': string,
  'version': string,
  'providerId': string,
  'statementId': string,
  'x-akoya-interaction-type': XAkoyaInteractionTypeEnum,
}

async function executeGetStatements(
  req: GetStatementsMCPToolRequest
): Promise<CallToolResult> {
  try {
    const response = await statementsController.getStatements(
      req['accountId'],
      req['version'],
      req['providerId'],
      req['statementId'],
      req['x-akoya-interaction-type']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    let errorMessage = "Something went wrong during tool execution.";
    if (error instanceof ApiError) {
      try {
        errorMessage = stringifyRawJson({
          statusCode: error.statusCode,
          headers: error.headers,
          body: error.body
        });
      } catch (stringifyError) {
        errorMessage = `API error occurred, but details could not be serialized. Message: ${stringifyError}`;
      }
      console.error("API Error:", {
        statusCode: error.statusCode,
        headers: error.headers,
        body: error.body
      });
    } else {
      console.error("Unexpected Tool Error:", error);
      if (error instanceof Error) {
        errorMessage = error.message;
      }
    }
    return {
      content: [{ type: "text", text: `Tool Error: ${errorMessage}` }],
      isError: true, // Indicate to the LLM that the tool failed
    };
  }
}

async function handleGetStatements(
  args: unknown | GetStatementsMCPToolRequest
): Promise<CallToolResult> {
  const validationSummary = schemas.validate(args, "Statements", "get-statements");
  if (!validationSummary.isValid) {
    if (validationSummary.errors) {
      return {
        content: validationSummary.errors,
        isError: true,
      };
    }

    return {
      content: [{ type: "text", text: "Invalid arguments for getStatements tool." }],
      isError: true,
    };
  }

  return await executeGetStatements(args as GetStatementsMCPToolRequest);
}

export async function statementsGetStatementsTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "statements-getStatements",
      description: `Retrieve a specific account statement file. Use [HTTP Accept request-header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) to specify desired content types. 

For the initial launch, only PDF statements are supported. PDFs are returned in the response.

### cURL request

We recommend using the auto-generated cURL request with the {idToken}, accountId, providerId, statementId, and version with an added cURL parameter to return the output to a file. For example:

\`\`\`curl
curl --request GET --url https://sandbox-products.ddp.akoya.com/statements/v2/mikomo/513815781465/P9CvLPKDaFRMbNDkhu1 --header "accept: application/pdf" --header "authorization: Bearer {idtoken}" --output example.pdf
\`\`\``,
      inputSchema: await schemas.loadSchema("Statements", "get-statements"),
    },
    handler: handleGetStatements,
  };
}

